### ISSUE TITLE
how to verify LPCNet 

### ISSUE THREAD

**Issue by fjfjfan** [onnx/keras-onnx#108]
Since there is just LPCNet for RNN testing in this project, I'd like to have a try, and following https://github.com/onnx/keras-onnx/blob/master/applications/lpcnet/README.md, I go to https://github.com/mozilla/LPCNet/, and build it 
```
./autogen.sh
./configure
make
```
but I did not find a way to install lpcnet for Python?
So when I run convert_lpcnet_to_onnx.py, always got error: ModuleNotFoundError: No module named 'lpcnet'

**Comment by jiafatom** [comment]
lpcnet is not a python package, just add its directory to your path.
