### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'type' during conversion

### ISSUE THREAD

**Issue by el1995** [onnx/keras-onnx#121]
Hello everyone,

I am trying to convert a keras .h5 model (pretrained) to onnx format. Depending on the target_opset-parameter I get varying errors, but most of the time the error is:

AttributeError: 'Tensor' object has no attribute 'type'

I attached both the .h5-file and my code in a zip file.

Tensorflow version is 1.5.0 (as my machine using Ubuntu 16.04 LTS does not support AVX), keras version is 2.1.2-tf.
Thanks for any help!

[ConversionError.zip](https://github.com/onnx/onnxmltools/files/3207397/ConversionError.zip)

**Comment by jiafatom** [comment]
@el1995 I see you are using opset=7 which is a bit old, can you try opset 10. Just use kera2onnx converter (see Readme) to convert it directly.

**Comment by jiafatom** [comment]
I just use the latest keras2onnx and it is working for me. Please update keras2onnx package and try converting use opset=10. Thanks.

**Comment by yonglizhong** [comment]
Hi. I have received the same error while trying to convert a keras model of YOLOv3 to onnx model with the the given yolov3.py provided. I am currently using onnx==1.6.0. Wondering if it worked for anyone.
