### ISSUE TITLE
Error when running test_ACGAN

### ISSUE THREAD

**Issue by ghgraham** [onnx/keras-onnx#160]
### System information
Red Hat Enterprise 7.4

### Describe the current behavior
I am interested in saving the generator of a gan to onnx format. I have sampled the code from applications/test_keras_applications.py for ACGAN. When I run the code, the code fails as below:

> Traceback (most recent call last):
  File "/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'sequential_1/batch_normalization_1/cond/FusedBatchNormV3/Switch_1' expects to be colocated with unknown node 'batch_normalization_1/gamma'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
File "test-acgan.py", line 35, in <module>
    onnx_model = keras2onnx.convert_keras(keras_model, keras_model.name)
  File "/lib/python3.6/site-packages/keras2onnx/main.py", line 92, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/lib/python3.6/site-packages/keras2onnx/parser.py", line 497, in parse_graph
    return _parse_graph_scope(graph, keras_op_table, topo, top_level, output_names)
  File "/lib/python3.6/site-packages/keras2onnx/parser.py", line 473, in _parse_graph_scope
    _convert_general_scope(nodes, varset)
  File "/lib/python3.6/site-packages/keras2onnx/parser.py", line 204, in _convert_general_scope
    subgraph, replacement = create_subgraph(sess.graph, node_list, sess, operator.full_name)
  File "/lib/python3.6/site-packages/keras2onnx/subgraph.py", line 132, in create_subgraph
    tf.import_graph_def(output_graph_def, name=im_scope)
  File "/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Node 'sequential_1/batch_normalization_1/cond/FusedBatchNormV3/Switch_1' expects to be colocated with unknown node 'batch_normalization_1/gamma'

### Code to reproduce the issue
```
import os
import sys
import onnx
import unittest
import keras2onnx
import numpy as np
from keras2onnx.proto import keras, is_tf_keras
from distutils.version import StrictVersion

latent_dim = 100
num_classes = 10
channels = 1
model = keras.models.Sequential()
model.add(keras.layers.Dense(128 * 7 * 7, activation="relu", input_dim=latent_dim))
model.add(keras.layers.Reshape((7, 7, 128)))
model.add(keras.layers.BatchNormalization(momentum=0.8))
model.add(keras.layers.UpSampling2D())
model.add(keras.layers.Conv2D(128, kernel_size=3, padding="same"))
model.add(keras.layers.Activation("relu"))
model.add(keras.layers.BatchNormalization(momentum=0.8))
model.add(keras.layers.UpSampling2D())
model.add(keras.layers.Conv2D(64, kernel_size=3, padding="same"))
model.add(keras.layers.Activation("relu"))
model.add(keras.layers.BatchNormalization(momentum=0.8))
model.add(keras.layers.Conv2D(channels, kernel_size=3, padding='same'))
model.add(keras.layers.Activation("tanh"))

noise = keras.layers.Input(shape=(latent_dim,))
label = keras.layers.Input(shape=(1,), dtype='int32')
label_embedding = keras.layers.Flatten()(keras.layers.Embedding(num_classes, 100)(label))

model_input = keras.layers.multiply([noise, label_embedding])
img = model(model_input)

keras_model = keras.models.Model([noise, label], img)
x = np.random.rand(1, 100).astype(np.float32)
y = np.random.rand(1, 1).astype(np.int32)

expected = keras_model.predict([x, y])
onnx_model = keras2onnx.convert_keras(keras_model, keras_model.name)
```
### Describe the expected behaviour
As this code forms a part of the unit testing which is passing, I am curious to know why it fails when running in isolation (@denfromufa)

Thanks for your advice on this.

**Comment by jiafatom** [comment]
Did you use the pypi keras2onnx? Can you pull latest keras2onnx master instead and try? We have some fixes recently.

**Comment by ghgraham** [comment]
Indeed I did install from pypi. I've installed direct from master and it working nicely. Thanks fro getting back to me so quickly and for the advice.
