### ISSUE TITLE
keras 

### ISSUE THREAD

**Issue by YUHANGZHANG7** [onnx/keras-onnx#167]
Hi, my model is based on Keras without using tenTensorFlow, can I use your method to transform my .h5 file and run it on the Tensor RT?
I mean only has a ***.onnx file can help me to complete the task?

**Comment by jiafatom** [comment]
Do you mean to convert the h5 file to onnx file? Yes, we can do that.

**Comment by YUHANGZHANG7** [comment]
> Do you mean to convert the h5 file to onnx file? Yes, we can do that.

Well, thank you. I mean that can I just use the ***.onxx file to complete Keras task on Tensor RT? In other words, dose it need other file to  support it? Such as .trt file or others.

**Comment by stevenlix** [comment]
You can try TensorRT tool onnx2trt to generate TensorRT engine *.trt from *.onnx model. No other file is needed.
