### ISSUE TITLE
 possible Python 2.7 compatibility issue when trying to install? TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by missaugustina** [onnx/keras-onnx#17]
I'm primarily an R user, so I don't use Python much except to install packages that I'll interface with in R. Apparently my Terminal is running Python 2.7 by default. If you don't support 2.7 then you should state it explicitly, otherwise it should probably be something you have test coverage for. Assuming that's the issue of course.. it could just be something broken on my end ;)

I'm trying to install on MacOS 10.14.2 via pip

➜  ~ pip install git+https://github.com/onnx/keras-onnx.git
Collecting git+https://github.com/onnx/keras-onnx.git
  Cloning https://github.com/onnx/keras-onnx.git to /private/var/folders/54/pl7mz_l161l58gbdbtw2qzbc0000gn/T/pip-req-build-ENv9ru
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/54/pl7mz_l161l58gbdbtw2qzbc0000gn/T/pip-req-build-ENv9ru/setup.py", line 34, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by jiafatom** [comment]
The code is tested on Python 3.5 and 3.6; we don't support Python 2.7. Just sent a PR to update Readme.md.

**Comment by missaugustina** [comment]
Issue #19

**Comment by jiafatom** [comment]
PR merged, close the issue.
