### ISSUE TITLE
Bidirectional-GRU

### ISSUE THREAD

**Issue by mxdilln** [onnx/keras-onnx#175]
Hello, when trying to convert a keras model to onnx I get the following error:

TypeError: The bidirectional module only works with LSTM in Keras but we got <class 'keras.layers.recurrent.GRU'

The GRU unit does work with the bidirectional module in Keras, could this be a bug in the code?

I note that the issue was reported last month here: https://github.com/onnx/keras-onnx/issues/98#issuecomment-498227397

Thanks!

**Comment by jiafatom** [comment]
Can you please share the model for us to debug? Thanks.

**Comment by mxdilln** [comment]
Sure, this is what I was using:

def rnn_1():

    model = Sequential()
    model.add(embedding_layer)

    model.add(Bidirectional(GRU(64, return_sequences=True)))
    model.add(BatchNormalization())

    model.add(Bidirectional(GRU(64, return_sequences=True)))
    model.add(GlobalMaxPool1D())
    model.add(BatchNormalization())

    model.add(Dense(32, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(len(primary_codes), activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
    print(model.summary())
    return model

**Comment by jiafatom** [comment]
Currently this Bidirectional-GRU is not supported, the current plan is that we may not support this in near future.

**Comment by mxdilln** [comment]
Are there any plans to support CUDA layers (CuDNNLSTM and CuDNNGRU)?

**Comment by jiafatom** [comment]
Unfortunately no plans for that.

**Comment by mxdilln** [comment]
Ok thanks. Can you confirm if they are supported in tf2onnx?
