### ISSUE TITLE
Converted ONNX model is not topologically sorted

### ISSUE THREAD

**Issue by benschreiber** [onnx/keras-onnx#184]
Similar issue to #170. I am trying to convert a Keras model that contains some LSTM layers followed by a TimeDistributed. I am using the latest version of keras2onnx on master, 1.5.2. The model converts without any errors, but when I later use the ONNX model checker on it, there is the output 
```
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'time_distributed_1/Reshape_1:01' of node: 
input: "time_distributed_1/Reshape_1:01" output: "time_distributed_1/Reshape_1:0" name: "Identity1" op_type: "Identity" domain: ""
 is not output of any previous nodes. 
```
When I converted the ONNX file to a pbtxt, the Identity node was the first one listed, when it should be at the end.

Here is my saved model:
[saved_model.zip](https://github.com/onnx/keras-onnx/files/3468957/saved_model.zip)

Unzip it and run this script to reproduce the behavior:
```
import keras
import onnx
import keras2onnx

saved_model = keras.models.load_model('saved_model.h5')
onnx_model = keras2onnx.convert_keras(saved_model, saved_model.name)
onnx.checker.check_model(onnx_model)
```

**Comment by jiafatom** [comment]
This is a known issue on onnx, not converter. Just run your model on onnxruntime, you can still get inference correctly.

**Comment by benschreiber** [comment]
I am doing development work that requires TensorRT. Please consider fixing this in keras-onnx or asking the onnx developers to prioritize this.

**Comment by gramalingam** [comment]
@jiafatom : Why is this an onnx issue? I think it is a converter issue. The ONNX specification clearly requires the nodes in a graph to be topologically sorted. The graph-construction utilities expect the same. So, it is the caller's responsibility to provide the nodes in topologically sorted order. (I agree that it would be useful to provide a topological-sort utility in ONNX to do the sorting, but it doesn't exist today.)

**Comment by jiafatom** [comment]
@benschreiber Just checked in the fix in onnxconverter_common, can you pull its master and try? We will release pypi package soon.

**Comment by benschreiber** [comment]
@jiafatom The conversion to ONNX now fails.
```
Traceback (most recent call last):
  File "lstm_autoencoder.py", line 236, in <module>
    onnx_model = keras2onnx.convert_keras(lstm_autoencoder, lstm_autoencoder.name)
  File "/home/bschreiber/converters/keras-onnx/keras2onnx/main.py", line 103, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/home/bschreiber/converters/keras-onnx/keras2onnx/topology.py", line 216, in convert_topology
    container.add_output(tensor_outputs[name])
  File "/home/bschreiber/converters/keras-onnx/keras2onnx/common/interim.py", line 192, in add_output
    self.outputs.append(self._make_value_info(variable))
  File "/home/bschreiber/converters/keras-onnx/keras2onnx/common/interim.py", line 173, in _make_value_info
    value_info.type.CopyFrom(variable.type.to_onnx_type())
  File "/home/bschreiber/anaconda3/lib/python3.7/site-packages/onnxconverter_common/data_types.py", line 87, in to_onnx_type
    raise ValueError('Unsupported dimension type: %s' % type(d))
ValueError: Unsupported dimension type: <class 'NoneType'>
```

**Comment by jiafatom** [comment]
@benschreiber I tried keras-onnx master, and it works correctly for me.

If you still cannot make it work, feel free to share the script (of keras model) with me, then I can add it to unit test.

**Comment by benschreiber** [comment]
@jiafatom I tried again with the new pypi version. It works again, and the model passes the ONNX checker. Thank you!
