### ISSUE TITLE
Onnx model converted from hdf5 model has lstm nodes with different dimensions for bias and kernel

### ISSUE THREAD

**Issue by tijithomas** [onnx/keras-onnx#214]
The keras model:
![Screenshot from 2019-08-29 11-43-42](https://user-images.githubusercontent.com/42336597/63916826-d5887980-ca56-11e9-99cf-247daee0af10.png)

After conversion, the onnx model has transpose after every node and the dimension for bias on lstm nodes have changed from [2000] to [1,4000]. Although after 2000, all the values are 0. Is the conversion correct in this case?
![Screenshot from 2019-08-29 11-52-39](https://user-images.githubusercontent.com/42336597/63917021-42037880-ca57-11e9-8367-17116c14c86b.png)

**Comment by jiafatom** [comment]
The dimension mismatch is because onnx and keras have different specs, please check onnx spec, it says the bias tensor has shape `[num_directions, 8*hidden_size]`, others are `4*hidden_size`, so it is 2x, which is correct.

**Comment by tijithomas** [comment]
@jiafatom Thanks for the quick reply! 
The hdf5 model has dynamic batch size(?) in input/output placeholder, the output placeholder of the converted onnx (same model as above) shows 0 as batch size.
![Screenshot from 2019-08-30 10-14-53](https://user-images.githubusercontent.com/42336597/63993634-26f43f80-cb0f-11e9-821a-346b9c2bc2ac.png)
Should it not be '-1' or '?' instead of '0'?

**Comment by jiafatom** [comment]
Can you pull latest keras2onnx master to try? It should be 'N' for both input and output batch.

**Comment by tijithomas** [comment]
Thanks, it works!
