### ISSUE TITLE
Error while converting other yolov3 model

### ISSUE THREAD

**Issue by amanarora28** [onnx/keras-onnx#227]
I followed the script shared to convert a newly trained yolov3 model. The conversion was successful but a problem arises when loading the model in onnxruntime.
Error:

RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Node:Identity2 Output:yolonms_layer_1/ExpandDims_1:0 [ShapeInferenceError] Mismatch between number of source and target dimensions. Source=3 Target=4

I have read a lot about this error, maybe onnx is not  able to figure out dimension change with expand dims operator. 
All I wanted to know is how can I skip this shape inference while loading model?

**Comment by wenbingl** [comment]
What's the version of onnxruntime?

**Comment by amanarora28** [comment]
The version is onnxruntime==0.4.0

**Comment by wenbingl** [comment]
The converted yolo-v3 mode has been run with ORT 0.5.0 and above.

**Comment by amanarora28** [comment]
The version is not a problem I guess.
I face the same issue with version 0.5.0

**Comment by amanarora28** [comment]
I have solved the issue though , there was some issue with your YOLONMSLayer and convert_NMSLayer. The shape of boxes_r was not consistent in them. Hence the error.
Now I don't face this issue. 
There were other issues as well when converting using onnx==1.5.0, like AddV2 is not supported.
I have solved all these issues and made a runnable script and converted my model to onnx.
Can I share the changes with you and you can verify them if I am not updating some undesired fields because the results I get are not too great in comparison to keras model.
Thanks anyways.

**Comment by wenbingl** [comment]
awesome! Can you submit a PR for your change to help other as well?

**Comment by amanarora28** [comment]
Sure, I will raise a PR.
I am also stuck on one other issue:
My older keras yolo model took 0.3-0.4 seconds on average for a prediction whereas onnx yolo model is taking 1.2-1.5 seconds for one prediction on CPU.
I shifted to onnx for speed improvement only but alas I see this. 
Can you tell me if I am misusing onnx and can decrease run time if possible?

**Comment by wenbingl** [comment]
@amanarora28 , Can you try the model in model zoo which was converted with some additional optimization?https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3 

If the optimized model meets your expectation, we will see how to add the optimization into the script as well.

**Comment by amanarora28** [comment]
I tried the optimised yolo-onnx model found here 
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3
in python and it was taking much larger time than other models(2-3 secs).
Can you guide me how to use C/C++ to run inference on onnx models?

**Comment by amanarora28** [comment]
@XuDongHecs I have added the changes here https://github.com/onnx/keras-onnx/pull/240
@wenbingl No, the model load time was certainly not included. The model was already loaded and made a 100 prediction requests one by one(sequentially) , all took > 2 seconds for your base yolo-onnx model. 
I have not yet tried the C++ code, because my working environment is python, but I can shift if it gives me good efficiency.

Also, I was wondering, are you working on optimising text models too, having LSTM layers ?

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/237)

**Comment by Rapternmn** [comment]
Check My repo for Yolov3 - Onnx Conversion
https://github.com/Rapternmn/PyTorch-Onnx-Tensorrt
