### ISSUE TITLE
ValueError: Unknown layer: Affine

### ISSUE THREAD

**Issue by caesar84** [onnx/keras-onnx#238]
hi there,
I am trying to convert a Keras model to ONXX on Ubuntu 16.04 and i had this error. any ideas what have i done wrong?

here is the output :

python3 test_1.py
/home/mastlab/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mastlab/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
WARNING:tensorflow:From /home/mastlab/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "test_1.py", line 5, in <module>
    model= load_model('/home/mastlab/Downloads/model.h5', compile=False)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 550, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 243, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 593, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/engine/network.py", line 1043, in from_config
    process_layer(layer_data)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/engine/network.py", line 1029, in process_layer
    custom_objects=custom_objects)
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/home/mastlab/.local/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Affine

**Comment by wenbingl** [comment]
You need specify the Affine layer code in the model_from_config/custom_objects. 
And this isn't related to any converter code.

**Comment by caesar84** [comment]
Thank you @wenbingl.
Could you elaborate more please because I couldn't get your point. What should I do to make this work?

**Comment by amanarora28** [comment]
@caesar84 you should load the model like this.
https://github.com/keras-team/keras/issues/4871#issuecomment-329392660
model = keras.models.load_model('model.h5', custom_objects={'Affine': Affine})

**Comment by caesar84** [comment]
hi @amanarora28 
thanks for your advice. 
here is the error I am facing now .


Traceback (most recent call last):
  File "test_1.py", line 10, in <module>
    model = keras.models.load_model('model.h5', custom_objects={'Affine': Affine})
NameError: name 'Affine' is not defined

**Comment by jiafatom** [comment]
Is Affine layer the custom layer you defined? If yes, Affine need point to that piece of code.
