### ISSUE TITLE
Causal Conv1D is not supported

### ISSUE THREAD

**Issue by AStupidBear** [onnx/keras-onnx#246]

**Comment by jiafatom** [comment]
Do you have a model that uses causal conv1d? Feel like this is not commonly used.

**Comment by AStupidBear** [comment]
> Do you have a model that uses causal conv1d? Feel like this is not commonly used.

**Comment by AStupidBear** [comment]
For example, [keras-tcn](https://github.com/philipperemy/keras-tcn).

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/272), can you pull latest keras2onnx master and try?

**Comment by jiafatom** [comment]
Just added keras-tcn into nightly build [here](https://github.com/onnx/keras-onnx/pull/277), it passes, so close the task.
