### ISSUE TITLE
pip install keras2onnx error

### ISSUE THREAD

**Issue by corleonechensiyu** [onnx/keras-onnx#278]
when i run `import keras2onnx',
'import onnx' ,
'from keras.models import load_model' ,
'model = load_model('model.h5')' ,
'onnx_model = keras2onnx.convert_keras(model)' ,
'temp_model_file ='model.onnx' ' ,
'onnx.save_model(onnx_model,temp_model_file)`,
it have this error .
`Traceback (most recent call last):
  File "E:/pytorchprojects/demo/keras2onnx.py", line 1, in <module>
    import keras2onnx
  File "E:\pytorchprojects\demo\keras2onnx.py", line 76, in <module>
    onnx_model = keras2onnx.convert_keras(model)
AttributeError: module 'keras2onnx' has no attribute 'convert_keras'`

**Comment by jiafatom** [comment]
Can you run the test examples in `test_layers.py`, `test_keras_applications.py`?

**Comment by corleonechensiyu** [comment]
> Can you run the test examples in `test_layers.py`, `test_keras_applications.py`? `keras2onnx.convert_keras` is used successfully there.

i install keras2onnx with pip，not source code.

**Comment by jiafatom** [comment]
This seems not a converter issue. You can try install it through github source.

**Comment by corleonechensiyu** [comment]
> This seems not a converter issue. You can try install it through github source.

yes,source code can work.why "pip install keras2onnx" can't work:(

**Comment by jiafatom** [comment]
Feel free to reopen if the issue still exists.

**Comment by orsveri** [comment]
I had this issue too. Reason is very stupid :D
It is because you named your script as 'keras2onnx.py' (like the package!) and python is trying to find 'convert_keras' function in your script, not in the package.
I named my script 'keras2onnx.py' too at first, but after I changed it to 'save_onnx.py', this problem was gone.

**Comment by WeberJulian** [comment]
It's still a problem today, I don't think the issue should be closed @jiafatom
