### ISSUE TITLE
Converted model produces different output

### ISSUE THREAD

**Issue by kurzacz** [onnx/keras-onnx#281]
I tried to convert Cat & Dog classifier from keras to onnx. Repository is pasted below:
https://github.com/girishkuniyal/Cat-Dog-CNN-Classifier

Net is built from Conv2D, MaxPooling2D, Flatten and Dense layers. Visualization from Tensorboard is below:
![cat-and-dogs](https://user-images.githubusercontent.com/46242461/67511808-f1477f00-f697-11e9-906b-879af81f23ca.png)

The problem is, model provided in repository correctly distinguishes a cat from a dog. It uses binary classification (1 = dog, 0 = cat). After conversion, onnx model every time outputs 1.

You can download project either from repository linked above or download whole project packed in zip file:
https://drive.google.com/open?id=1fNrhBm23I91BgUBRjw3PeXb0N3wL35Ru
My zip file is extended with sample images of a cat and a dog, and 2 scripts:

- onnx-conv.py is a script based on your tutorial how to convert model from Keras to ONNX. When you run it, it will try to classify images of a cat and a dog. You can expect for both images the output is 1. This is basically my problem, because for a cat it should output 0.
- model-test.py - quick script to test model I'm trying to convert. I used this script to ensure that Keras model works properly, that is, gives output 0 for a cat and output 1 for a dog.

**Comment by jiafatom** [comment]
Just add `pred_keras = model.predict(x)` in `onnx-conv.py` and find that the keras result every time output 1 too. why you see output 0?

**Comment by kurzacz** [comment]
Oh yes, you're right. When I compare preprocessing input in `onnx-conv.py` and `model-test.py` I see there was no preprocessing step. I didn't notice that this line:
x = preprocess_input(x)
was actually specific for resnet50 network from the example.

I'm sorry for bothering you. Topic is to be closed.
