### ISSUE TITLE
SpatialDropout2D not supported

### ISSUE THREAD

**Issue by lpj0822** [onnx/keras-onnx#303]
SpatialDropout2D not support?

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/305), can you pull latest keras2onnx master and try?

**Comment by lpj0822** [comment]
I use 1.6.0

**Comment by jiafatom** [comment]
The fix is newly added so it is not in 1.6.0. You need pull latest keras2onnx master or wait for 1.6.1.

**Comment by jiafatom** [comment]
keras2onnx 1.6.5 just released, it should work.
