### ISSUE TITLE
module 'keras.applications.mobilenet' has no attribute 'relu6'

### ISSUE THREAD

**Issue by corleonechensiyu** [onnx/keras-onnx#316]

**Comment by jiafatom** [comment]
Which keras version you use? Try keras 2.2.4+

**Comment by Royzon** [comment]
@jiafatom I meet the same problem when I use keras 2.3.1

**Comment by jiafatom** [comment]
Can you share the script for your model so that we can debug this? Thanks.

**Comment by jiafatom** [comment]
keras2onnx 1.6.5 just released, it should work.
