### ISSUE TITLE
RuntimeError: Unsupported activation method within Activation layer '<function relu6 at 0x7f0c5dfe03b0>'

### ISSUE THREAD

**Issue by Royzon** [onnx/keras-onnx#325]
I meet this problem when I run the [test_segnet.py](https://github.com/onnx/keras-onnx/blob/master/applications/nightly_build/test_segnet.py). what makes me Incomprehensible is that you said the latest version of keras supports relu6 [here](https://github.com/onnx/keras-onnx/issues/316#issuecomment-567621840)，so why does this problem still occur? here is my config information:
keras=2.3.1
kears2onnx=1.6.0
onnxruntime=1.1.0
onnx=1.6.0
onnxconverter-common=1.6.1

**Comment by jiafatom** [comment]
The `relu6` in `test_segnet` is defined by the author of `keras_segmentation`. I just checked in the [fix](https://github.com/onnx/keras-onnx/pull/326) and add the `mobilenet_segnet` into our nightly build and it passed. Please pull `keras2onnx` and `onnxconverter-common` master to test to see if it works.

**Comment by jiafatom** [comment]
keras2onnx 1.6.5 just released, it should work.

**Comment by temptitle** [comment]
keras2onnx-1.7.0 onnxconverter-common-1.7.0

RuntimeError: Unsupported activation method within Activation layer '<function relu at 0x000001ED0DBCAAE8>'
