### ISSUE TITLE
 yolov3  Inputs error

### ISSUE THREAD

**Issue by devinhee** [onnx/keras-onnx#332]
when I tried to test yolov3. an error occurred.
"../keras_onnx/keras2onnx/common/interim.py", line 134, in add_node
raise ValueError('Inputs must be a list of string but get [%s]' % type_list)
ValueError: Inputs must be a list of string but get [<class 'list'>,<class 'str'>]
"
then I print "Inputs", they are not always one-dimensionnal, sometime Inputs like this:
" [['yolo_evaluation_layer_1/mul_5:0'], 'shape_tensor'] "
so I tried to flatten them into one-dimensional, but it didn't work, there were some new errors occurred. 
the "desired_shape" got a string after "inputs: ['yolo_evaluation_layer_1/Reshape_3/shape:0']"

Now I'm a little confused, there isn't any chance to make a change yet. 
Is this caused by my input image? (I just input the "data/street.jpg" )
Any suggestion?
Thank your!

**Comment by jiafatom** [comment]
Please try keras2onnx and onnxconverter-common master branch. This is running on nightly build, so should work.

**Comment by devinhee** [comment]
> Please try keras2onnx and onnxconverter-common master branch. This is running on nightly build, so should work.

Yeah, I did try keras2onnx master branch, but it still had the same issue.  Anyway thanks.

**Comment by devinhee** [comment]
This time it works!
Thanks so much.
