### ISSUE TITLE
Assertion Error when converting simple tf.keras model to onnx

### ISSUE THREAD

**Issue by mxdillon** [onnx/keras-onnx#339]
**Describe the bug**
When converting a simple tf.keras model to onnx, the following error appears:

```There is an error(<class 'AssertionError'>) happened during optimizing on the converted model!```

Despite the error, the model does convert and save, but when checking the saved model with `onnx.checker.check_model(model)`, the following error is given:

`onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'sequential/dense_1/Softmax:0' of node: 
input: "sequential/dense_1/Softmax:0" output: "output_1" name: "Identity7" op_type: "Identity" domain: ""
 is not output of any previous nodes.`

This might be relevant to the issue?

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.2
- onnx version: 1.6.0
- keras2onnx version: 1.6.0
- Python version: 3.7.2 64-bit
- Visual Studio version (if applicable): Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

- CUDA/cuDNN version: na
- GPU model and memory: na

**To Reproduce**
Error reproduced with the following code and packages:

```
onnx==1.6.0
keras2onnx==1.6.0
tensorflow==1.15.0
onnxruntime==1.1.0
```

```
import os
import tensorflow as tf
import keras2onnx
import onnx
import onnxruntime

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]


train_ds = (
    tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(10000).batch(32)
)
test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

history = model.fit(train_ds, epochs=1)

onnx_model = keras2onnx.convert_keras(model)
onnx.save_model(onnx_model, 'model_keras.onnx')

model = onnx.load("model_keras.onnx")
onnx.checker.check_model(model)

```

**Expected behavior**
Expected the model to convert without errors and then run in an onnxruntime session

**Comment by jiafatom** [comment]
Can you pull latest keras2onnx master and onnxconverter-common master and try?

**Comment by mxdillon** [comment]
Thanks for the suggestion. Have tried it and am still getting the same error.

**Comment by jiafatom** [comment]
Please specify `input_shape` at the first layer so that the layers can have inbound nodes, for example, Change `tf.keras.layers.Flatten()` to `tf.keras.layers.Flatten(input_shape=(28, 28, 1))`, then it works.

**Comment by mxdillon** [comment]
This change still gives the `Assertion Error` when converting the model, and when loading and checking the model, the error has changed slightly to:

```
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'dense_1/Softmax:0' of node: 
input: "dense_1/Softmax:0" output: "dense_1" name: "Identity5" op_type: "Identity" domain: ""
 is not output of any previous nodes.
```

**Comment by mxdillon** [comment]
Apologies - my mistake. This has solved the issue, thanks!
