### ISSUE TITLE
Yolov3: INVALID_GRAPH : This is an invalid model

### ISSUE THREAD

**Issue by AndresOsp** [onnx/keras-onnx#344]
If I use the Yolov3 script from: [keras-yolo3](https://github.com/qqwweee/keras-yolo3) Then, I transform the model to onnx IT WORKS. However, the output of that model does not have the evaluation layer nor the non max suppression layer. Then post-processing should be applied.

In this repository the [test](https://github.com/onnx/keras-onnx/blob/master/applications/nightly_build/test_yolov3.py) and the [script for yolov3](https://github.com/onnx/keras-onnx/tree/master/applications/yolov3). That in my understanding are complementary. When I run the test it gives me the following error:

```
ERROR: test_yolov3 (__main__.TestYoloV3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "yolo2onnx2.py", line 90, in test_yolov3
    sess = onnxruntime.InferenceSession(temp_model_file)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:TFNodes/yolo_evaluation_layer_1/add_2 : No Op registered for AddV2 with domain_version of 11
```
Apparently the operations in the evaluation layer are not implemented?, if that is the case how the test could be working?

Hope that I made some mistake (it would run much faster with the integrated evaluation)

Thanks for the help

**Comment by jiafatom** [comment]
Yolov3 onnx model is in model zoo [here](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3). 
This `test_yolov3.py` is running smoothly on nightly build pipeline every day. We save the yolov3 keras model in `YOLOV3_WEIGHTS_PATH`, can you compare if your yolov3 keras model the same as the one we have there?

**Comment by AndresOsp** [comment]
@jiafatom thanks for your time,

I downloaded the model, it works fine and has the evaluation layers. 

I tried many things without success. If I just run the (Yolo)[https://github.com/onnx/keras-onnx/tree/master/applications/yolov3] as instructed and I have the same error. 

My problem is that I am not working on nightly build pipeline.

I am having troubles in running the nightly build pipeline:
- Install the keras2onnx repository as `pip install git+https://github.com/onnx/keras-onnx`
- Install the onnxconverter-common repository as `pip install git+https://github.com/microsoft/onnxconverter-common`
- Then run and I have the same problem.

What am I doing wrong?
Thanks

**Comment by AndresOsp** [comment]
My mistake was that I was not on nightly build pipeline. Now it woks. Thanks
