### ISSUE TITLE
tf.keras trained on a GPU

### ISSUE THREAD

**Issue by mxdilln** [onnx/keras-onnx#378]
Are tf.keras models trained on a GPU supported?

I am training the below model on a Tesla V100-SXM2-16GB GPU:

```
        self.model = tf.keras.models.Sequential([
            tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
            tf.keras.layers.Dense(128, activation="relu"),
            tf.keras.layers.Dropout(0.2),
            tf.keras.layers.Dense(10, activation="softmax"),
        ])

        self.model.compile(optimizer="adam",
                           loss="sparse_categorical_crossentropy",
                           metrics=["accuracy"])
``` 

and it is successfully converting to onnx using: 

```
onnx_model = keras2onnx.convert_keras(self.model)
onnx.save_model(onnx_model, "model.onnx")
```

however when trying to load the model for inference, using:

```model = onnx.load("model.onnx")```

I get the following error:

```
Traceback (most recent call last):
  File xxx, line 19, in __init__
    model = onnx.load("model.onnx")
  File "xxx/venv/lib/python3.7/site-packages/onnx/__init__.py", line 115, in load_model
    model = load_model_from_string(s, format=format)
  File "xxx/venv/lib/python3.7/site-packages/onnx/__init__.py", line 152, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "xxx/venv/lib/python3.7/site-packages/onnx/__init__.py", line 95, in _deserialize
    decoded = cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message
```

A very similar process has worked successfully when training on a CPU, so I am wondering if this has something to do with the model being trained on a GPU? 

I note that I previously had an issue (https://github.com/onnx/keras-onnx/issues/181) where (unsupported) CUDA layers were successfully converting to onnx using this package but then failing to load when I wanted to run inference.

**Comment by wenbingl** [comment]
interesting, can you post the converted onnx file in here?Normally the converter doesn't call any stuff in CUDA.

**Comment by mxdilln** [comment]
Sure:
[model.onnx.zip](https://github.com/onnx/keras-onnx/files/4194111/model.onnx.zip)

**Comment by wenbingl** [comment]
this file looks truncated. Can you run some tool like onnx.check to see if the model in the momory is already corrupted.

**Comment by mxdilln** [comment]
I think this error was caused by training the model on a GPU and trying to run inference on a CPU. Running inference on a GPU eliminated the issue.
