### ISSUE TITLE
Version 1.6.5 is not available at https://pypi.org/project/keras2onnx/#history

### ISSUE THREAD

**Issue by dmo2000** [onnx/keras-onnx#379]
I am trying to install version 1.6.5 of this library but it is not available at https://pypi.org/project/keras2onnx/#history.

Should I add another package manager in my system?

**Comment by wenbingl** [comment]
Sorry, due to some process issue, the package publish in pypi.org has been postponed for couple weeks.
You can try it from https://github.com/onnx/keras-onnx/releases or install it from the code with a version tag like pip install git+https://github.com/onnx/keras-onnx.git@v1.6.5

**Comment by dmo2000** [comment]
@wenbingl thanks for the information.

In order to work I had to execute also "pip install git+https://github.com/microsoft/onnxconverter-common.git@v1.6.5".

**Comment by jiafatom** [comment]
keras2onnx 1.7.0 is released now.
