### ISSUE TITLE
Output is different before and after model converted

### ISSUE THREAD

**Issue by WenyuZhu** [onnx/keras-onnx#382]
I'm trying to convert a pretrained ResNet50 model to onnx model for my UWP application. As WinML required, the input image format has to be 'channels_first', so I set set_image_data_format in Keras beackend as 'channels_first'. 
`K.set_image_data_format('channels_first')`
Then, pretrained ResNet50 model is loaded:
`from keras.applications.resnet50 import ResNet50
model = ResNet50(include_top=True, weights='imagenet')`
Load the test image:
`image_path = "predictTest.jpg"`
`img = image.load_img(image_path, target_size=(img_width, img_height))`
`data = image.img_to_array(img)`
`plt.imshow(img)`
`data = np.expand_dims(data, axis=0)`
`data = preprocess_input(data, data_format= 'channels_first')`
`result = model.predict(data)`
`print(result)`
`plt.title(result)`
`plt.show()`

Convert the model to onnx and predict:
`onnx_model = keras2onnx.convert_keras(model, model.name)`
`runtime prediction`
`content = onnx_model.SerializeToString()`
`sess = onnxruntime.InferenceSession(content)`
`data = data if isinstance(data, list) else [data]`
`feed = dict([(input.name, data[n]) for n, input in enumerate(sess.get_inputs())])`
`pred_onnx = sess.run(None, feed)`
`print(pred_onnx)`
I compared the result from Keras and onnx, They are not exactly the same.

Keras:

> [5.4314226e-04 5.9276802e-04 5.7217164e-04 4.9989636e-04 6.7251432e-04 ......]

Onnx:

> [4.46889459e-08, 3.85216566e-07, 3.61494085e-06, 5.48398518e-08, ......]

Also, I tried to replace the output layer with a 5-output 'softmax' layer, because I only need 5 classes, the output value became digital, and it's different from the result from Keras model before it's converted.
Keras:

> [[0.19099472 0.27407214 0.13260843 0.13774054 0.26458415]]

Onnx:

> [[0.0000000e+00 9.9999762e-01 0.0000000e+00 0.0000000e+00 2.4337219e-06]]

Did I do anything wrong here?

**Comment by wenbingl** [comment]
Which inference engine are you using to generate the result from the ONNX model?


We had ResNet50 test cases here: https://github.com/onnx/keras-onnx/blob/1a1945129dd45a660662b9144845bca13c622ae9/applications/nightly_build/test_keras_applications.py#L65 

Can you try it out?

**Comment by WenyuZhu** [comment]
@wenbingl I didn't use any inference engine, just ran the models with same image separately in a project.

How do I use 

> keras-onnx/applications/nightly_build/test_keras_applications.py

exactly?

I imported this class in a project, but it gave me an error:

> AttributeError: 'TestKerasApplications' object has no attribute 'model_files'

**Comment by WenyuZhu** [comment]
@wenbingl I have tried 
> https://github.com/onnx/keras-onnx/blob/1a1945129dd45a660662b9144845bca13c622ae9/applications/nightly_build/test_keras_applications.py#L65

and it passed the test. So, what would be the reason that cause the difference of my results? What should I do to prevent that?

**Comment by wenbingl** [comment]
The test case did the exact same thing as your code. Can you debug your code and compare to the test_ResNet50 to see what the issue comes from?

**Comment by WenyuZhu** [comment]
@wenbingl I just check both code files and they are almost same. Here is my code:
`model = keras.applications.resnet.ResNet50(include_top=True, weights='imagenet', input_tensor=None, input_shape=(img_width, img_height, 3), pooling=None, classes=1000)`
`# convert to numpy array`
`image_path = "predictTest10.jpg"`
`img = image.load_img(image_path, target_size=(img_width, img_height))`
`data = image.img_to_array(img)`
`data = np.expand_dims(data, axis=0)`
`result = model.predict(data)`
`print(result)`
`# convert to onnx model`
`onnx_model = keras2onnx.convert_keras(model, model.name, target_opset=7)`
`# runtime prediction`
`content = onnx_model.SerializeToString()`
`sess = onnxruntime.InferenceSession(content)`
`data = data if isinstance(data, list) else [data]`
`feed = dict([(input.name, data[n]) for n, input in enumerate(sess.get_inputs())])`
`pred_onnx = sess.run(None, feed)`
`print(pred_onnx)`
The two results are 
Keras model:
[[4.5873795e-04 5.4523529e-04 5.1445322e-04 4.5554299e-04 6.2101759e-04 ......]]
ONNX model:
[[1.63686291e-08, 1.59769598e-07, 1.72592968e-06, 2.08509530e-08, 1.92900956e-07, ......]]
I don't see any difference here from the code on Github.

However, I found an interesting thing. I trained a customized ResNet50 model instead of using fined tuned model with 'Imagenet' weights, and I got two same results:
Keras model:
[[0.17119987 0.27792943 0.070129   0.04630802 0.43443364]]
ONNX model:
[[0.17119952, 0.27793017, 0.07012897, 0.04630808, 0.4344332 ]]

Do you know what is the reason for this?

**Comment by wenbingl** [comment]
target_opset=7 is the only difference that I can find. can you try target_opset=10?

**Comment by WenyuZhu** [comment]
@wenbingl I just checked. The result from 'target_opset=10' and 'target_opset=7' are the same.

**Comment by jiafatom** [comment]
I tried both target_opset=10 and 7 by plugging your code
`model = keras.applications.resnet.ResNet50(include_top=True, weights='imagenet', input_tensor=None, input_shape=(img_width, img_height, 3), pooling=None, classes=1000)`
in the unit test `test_ResNet50` , both passes the unit test. I feel that the issue may be in your script. 

Btw, seems it should be `keras.applications.resnet50.ResNet50` not ` keras.applications.resnet.ResNet50`

**Comment by WenyuZhu** [comment]
@jiafatom I created a new project with the exactly same old code, and I finally got a correct result. I still don't know the reason for this. Anyway, thank you for look into my questions!

Closing this issue.
