### ISSUE TITLE
There is an error(<class 'AssertionError'>) happened during optimizing on the converted model!

### ISSUE THREAD

**Issue by tpengti** [onnx/keras-onnx#384]
my code:
def center_weighted_mse_loss(y_true, y_pred):
    mask = K.random_normal(K.shape(y_true))
    mask = K.cast(K.greater(mask, 0.8), 'float32')
    # weigh the center more
    radius=8
    center = np.zeros((K.int_shape(y_pred)[1],K.int_shape(y_pred)[2],1))
    center[K.int_shape(y_pred)[1] // 2 - radius : K.int_shape(y_pred)[1] // 2 + radius,
          K.int_shape(y_pred)[2] // 2 - radius : K.int_shape(y_pred)[2]// 2 + radius,:] = 1
    center =  mask + 10*K.variable(center)
    return K.mean(center * K.square(y_pred - y_true), axis=-1)
class L2_Normalization_Layer(keras.engine.Layer):
    '''
        This layer does L2 Normalization.
    '''
    def __init__(self, **kwargs):
        self.scale = True
        super(L2_Normalization_Layer, self).__init__(**kwargs)

    def compute_output_shape(self, input_shape):
        return input_shape

    def build(self, input_shape):
        if self.scale:
            self.alpha = self.add_weight(shape=[1, ],
                                         name='alpha',
                                         initializer=keras.initializers.RandomUniform(minval=10.0, maxval=20.0, seed=None))
        else:
            self.alpha = 1.0

    def call(self, x):
        return self.alpha * keras.backend.l2_normalize(x, -1)

model = load_model('/home/aistudio/work/cnn/pretrained_gmn.h5', custom_objects={'L2_Normalization_Layer': L2_Normalization_Layer, 'center_weighted_mse_loss': center_weighted_mse_loss})
#model = load_model('/home/aistudio/work/cnn/pretrained_gmn.h5')  
onnx_model = keras2onnx.convert_keras(model, model.name)
temp_model_file = '/home/aistudio/work/cnn/pretrained_gmn.onnx'
onnx.save_model(onnx_model, temp_model_file)

Perform conversion output information：

The tf.op node image_f_l2/l2_normalize/Square of type Square cannot be converted
The tf.op node exemplar_l2/l2_normalize/Square of type Square cannot be converted
There is an error(<class 'AssertionError'>) happened during optimizing on the converted model!

Traceback (most recent call last):
  File "/opt/conda/envs/py6/lib/python3.6/site-packages/keras2onnx/topology.py", line 305, in convert_topology
    outputs=container.outputs)
  File "/opt/conda/envs/py6/lib/python3.6/site-packages/onnxconverter_common/optimizer.py", line 915, in optimize_onnx
    [] if outputs is None else [o_.name for o_ in outputs])
  File "/opt/conda/envs/py6/lib/python3.6/site-packages/onnxconverter_common/optimizer.py", line 269, in build_from_onnx
    assert var_ == '' or var_ in inputs
AssertionError

Looking forward for your response, thank you

**Comment by jiafatom** [comment]
Thanks for reporting, need add tf.op Square conversion according to log.

**Comment by jiafatom** [comment]
tf.Square conversion is already in, please pull latest keras2onnx master and try again.
