### ISSUE TITLE
Import keras2onnx problem

### ISSUE THREAD

**Issue by chiehpower** [onnx/keras-onnx#403]
I followed both instructions to install keras2onnx.  (I already tried these methods of pip install and install from source.)
```
Building wheels for collected packages: keras2onnx
  Building wheel for keras2onnx (setup.py) ... done
  Created wheel for keras2onnx: filename=keras2onnx-1.6.5-py3-none-any.whl size=91201 sha256=4f513cbe863b2a3b18f15ebc55a2692467c969e95eb12bccf17e3881f5f61c25
  Stored in directory: /tmp/pip-ephem-wheel-cache-3enk0kv_/wheels/51/4f/28/887336f4f552370a09f70a60419f5af6f6202b71fe5999f612
Successfully built keras2onnx
Installing collected packages: keras2onnx
  Attempting uninstall: keras2onnx
    Found existing installation: keras2onnx 1.6.0
    Uninstalling keras2onnx-1.6.0:
      Successfully uninstalled keras2onnx-1.6.0
Successfully installed keras2onnx-1.6.5
```

When I test on python3, it cannot correctly import keras2onnx.
```
$ python3                                                              
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras2onnx
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/__init__.py", line 34, in <module>
    from .main import convert_keras
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/main.py", line 12, in <module>
    from .ke2onnx import static_set_ke2onnx_converters
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/ke2onnx/__init__.py", line 6, in <module>
    from .main import keras_layer_to_operator
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/ke2onnx/main.py", line 151, in <module>
    _layer.DepthwiseConv2D: convert_keras_depthwise_conv_2d,
AttributeError: module 'keras.layers' has no attribute 'DepthwiseConv2D'
```
Is there any idea about this wrong?
Thanks in advanced.

**Comment by jiafatom** [comment]
This is about keras layer, please check your keras installation.

**Comment by wenbingl** [comment]
what's your keras version, for the error, it looks the keras version is a little bit old.

**Comment by chiehpower** [comment]
> This is about keras layer, please check your keras installation.

Hi @jiafatom, I thought that my Keras installation should be quite correct. I can run the Mattorport's MRCNN which is used by Keras.  

> what's your keras version, for the error, it looks the keras version is a little bit old.

Hi @wenbingl, My keras version is 2.1.3. I have to use this version because I need to execute this sample of MaskRCNN which is provided by TensorRT. It requests us to use 2.1.3 version. (Please check [here](https://github.com/NVIDIA/TensorRT/blob/b44715656a81afe30f8e9a363ada5edf749e9335/samples/opensource/sampleUffMaskRCNN/converted/requirements.txt#L1).)

If we use keras2onnx, should we require to install which Keras version at least?

**Information of environment version**  
```
My TensorFlow version is 1.14
Ubuntu 18.04
Python 3.6.9
```

Thank you.

**Comment by jiafatom** [comment]
keras 2.1.3 is a bit outdated, please try keras 2.2.4.

**Comment by chiehpower** [comment]
After I upgraded to Keras 2.2.4, it could work well.
Thanks for your help!

If you can, I suggest that add this condition like `keras >=2.2.4` in [requirement.txt](https://github.com/onnx/keras-onnx/blob/master/requirements.txt). 

Thanks!
