### ISSUE TITLE
Can't parse model from keras2onnx with protocol buffers

### ISSUE THREAD

**Issue by Seraphid** [onnx/keras-onnx#448]
I created a model with the following code, and exported it to an onnx file
```
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
import onnx
import keras2onnx

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10)
])

onnx_model = keras2onnx.convert_keras(model, model.name)
onnx.save_model(onnx_model, 'tf1.onnx')
```
Now, I am trying to load it with my own code in c++, using the following code:

```
std::string path = 'tf1.onnx'
// Verify that the version of the library that we linked against is
// compatible with the version of the headers we compiled against.
GOOGLE_PROTOBUF_VERIFY_VERSION;
onnx::ModelProto model;
 
{
    // Read the existing net.
    fstream input(path , ios::in | ios::binary);
    if (!model.ParseFromIstream(&input))
        cerr << "Failed to parse model." << endl;
}
```

After running the c++ code, I get "Failed to parse model", that means that the parsing fails. This works for several other models parsed from other libraries, like pytorch, mxnet or eddl.

I have tried using onnx.proto and onnx.proto3 from https://github.com/onnx/onnx/tree/master/onnx to generate the headers and the source used for parsing the model, but none will work. Do you have any idea of why does the parsing fail?

Thanks in advance

**Comment by wenbingl** [comment]
Can you compare your C++ implementation to this https://github.com/onnx/onnx/blob/e2e12d97af735b8d25ecdbd8cf013c18d5b8d44f/onnx/checker.cc#L775 understand why?

**Comment by Seraphid** [comment]
The problem was with some dependencies. Having installed two different versions of protobuf in root and a conda environment created some unseen conflicts that effected this error. Nevertheless after removing both versions and reinstalling protobuf it ran fine.
