### ISSUE TITLE
How to remove Transpose Layer after transfer to onnx

### ISSUE THREAD

**Issue by DanielXu123** [onnx/keras-onnx#458]
I have succesfully transfered my tf.keras built .h5 model to .onnx file. Furthermore, **I need to transfer this .onnx file to .caffemodel and .prototxt.** It turns out that the onnx2caffe project shows 

`TypeError: ONNX node of type Transpose is not supported.`

I went back to check where the transpose comes from, bu**t there is no Transpose layer in my tf.keras net structure**.

May I ask how can I remove the Transpose Layer?

**Comment by jiafatom** [comment]
The generated onnx model may have Transpose node, because the input must be NCHW format for many ops, but keras model can have both NCHW or NHWC as input. So you should not remove Transpose node from onnx model. Actually Transpose is a common op, why onnx2caffe does not support it?

**Comment by DanielXu123** [comment]
I get the your point. But I just stuck in here. The onnx2caffe project I used is as following.
https://github.com/MTlab/onnx2caffe
Is there any way to transfer keras model to caffemodel directly ?

**Comment by DanielXu123** [comment]
I use the tensorflow as the backend to build the tf.keras sturcture, so in default for tensorflow, it will use NHWC, which is channel last.

**Comment by jiafatom** [comment]
This issue seems out of scope of keras2onnx, because (1) onnx model has to introduce Transpose after conversion. (2) ideally keras to caffe is a different topic. One work around (although not convenient) may be that we train the tensorflow model using NCHW, and then convert to onnx.

**Comment by DanielXu123** [comment]
I tried set the trained data as channel first type by adding 
`tf.keras.backend.set_image_data_format('channels_first')`
But it turns out more Transpose Layers show up, :( 

I may try using keras2caffe to transfer my model.
Very appreciate for your reply!

**Comment by avinash31d** [comment]
Training with channel_first does not remove transpose layers

**Comment by DanielXu123** [comment]
@avinash31d , Hi , Have you figured how to get rid of the transpose layer. I've tried using keras2caffe to transfer my tf.keras .h5 model to caffemodel , but the prediction results are not same.

**Comment by ruabliuqiu** [comment]
Hi,@DanielXu123.
Whether your problem has been solved?I come across the same problem. 
There is a transpose operation before the output.

**Comment by pustar** [comment]
Has anybody solve the problem? I come across the same problem.
There is a transpose operation before the output.

**Comment by pustar** [comment]
Has anybody solve the problem? I come across the same problem.
There is a transpose operation before the output.
