### ISSUE TITLE
not being able to convert a .h5 model (generated by tf.keras) using keras2onnx

### ISSUE THREAD

**Issue by Debottam** [onnx/keras-onnx#461]
Dear developers,

I have an .h5 model generated by tensorflow.keras (TF2.1). I have tried the following

```
keras2onnx.convert_keras(model,model.name)

Exception: This is a tensorflow keras model, but keras standalone converter is used. Please set environment variable TF_KERAS = 1.
```
Then I tried the following suggested in som stackoverflow answers

```
os.environ['TF_KERAS'] = '1'
keras2onnx.convert_keras(model,model.name)
```
But the exception still persists. Let me know if you need more details.

Thanks,
Debo.

**Comment by jiafatom** [comment]
This is the same issue as [here](https://github.com/onnx/keras-onnx/issues/451).
(1) At this time, please always pull latest keras2onnx master and onnxconverter-common master.
(2) Please set `TF_KERAS` before importing keras2onnx.

**Comment by Debottam** [comment]
Hi @jiafatom ,
Thanks it worked. I am closing this issue.
