### ISSUE TITLE
Changing channel ordering to NCHW

### ISSUE THREAD

**Issue by anilsathyan7** [onnx/keras-onnx#474]
How should we specify **'param channel_first_inputs: A list of channel first input**' parameters to change the channel ordering of all the layers so that there is no 'transpose layers' in the onnx model??

I tried to convert a tf.keras mode as follows
`onnx_model7 = keras2onnx.convert_keras(slim_model,'testt', channel_first_inputs=['ip','conv2d_transpose_4'])`

But the output still seems to have channel last format? I have previously tried[ tf2onnx](https://github.com/onnx/tensorflow-onnx) and in a similar manner  i managed to remove all except one transpose layer at output node.
[slim-net-157-0.02.zip](https://github.com/onnx/keras-onnx/files/4570210/slim-net-157-0.02.zip)

I'am using tf.15 with tf.keras and i need all layers with NCHW format with no transpose nodes? 
How can we achieve this?

**Comment by wenbingl** [comment]
The current argument only supports the input, and outputs needs some extra work.

**Comment by anilsathyan7** [comment]
I got it working... We just need to add one premute layer at the end in keras model. After that the onnx conversion does not create transpose layer at output end. But in some networks internal transpose nodes(pairs) still get created.

**Comment by DanielXu123** [comment]
Hi @anilsathyan7 . Could you pls show how you add the premute layer in tf.keras??
I have three Transpose layers after translate the model to onnx. 
I need transfer the tf.keras trained  model to caffe(which is channel first format). I can't get the same results with keras .h5 model and caffemodel. I'm wondering if the format make any difference

**Comment by anilsathyan7** [comment]
Hi @DanielXu123  here is an example for converting keras nhwc to onnx nchw format: [ipynb](https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/deepstream_multiseg/onnx_nchw_conversion.ipynb). This is a demo script for convertng a segmentation model trained in keras.

You need to specify channel first option for input during conversion and add permute layer at end of keras model for output(i.e before conversion).

**Comment by DanielXu123** [comment]
I checed the scripts, it seems we need to load the trained model and then add the permute layer. After that, we transfer this new combined model to onnx and define the input as channel first format. Is it correct?

**Comment by anilsathyan7** [comment]
Yes, atleast that worked for me and there were no redundant transpose layers after conversion, inside the onnx model.
