### ISSUE TITLE
Tensor {} already processed

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/keras-onnx#479]
I am getting below error while converting some of our model.
....keras2onnx/common/intop.py", line 71, in add_output
    assert False, "Tensor {} already processed".format(var.full_name)
AssertionError: Tensor .....0 already processed

Seems the issue is here:
https://github.com/onnx/keras-onnx/blob/master/keras2onnx/common/intop.py#L72
Anyway we are not reading 'op_from' else where. 

As we are reading it anywhere can we handle it in the same way as we are handling output_mask like:
a. https://github.com/onnx/keras-onnx/blob/master/keras2onnx/common/intop.py#L82
or 
b. can we make 'op_from' list like 'op_to'?

Also, why are we setting op_from again in shape_inference
https://github.com/onnx/keras-onnx/blob/master/keras2onnx/parser.py#L357
I am not able to understand the need for that here?

**Comment by wenbingl** [comment]
op_from is helping debugging the issue and preventing the any error happens on parsing. And the shapeInference happens after the parsing, so it doesn't trigger the issue you encountered.

So if you encounter the assertion error, it mostly like there is some error on parsing the original model, you can try it debug the parsing result by pass an argument debug_mode=true to output all tensor information and operation information. Or you can share some the model source code and we can help to check whether there is a bug in the parsing code.

**Comment by buddhapuneeth** [comment]
@wenbingl thanks for your insights. I would like to know more on this:
1. Can you provide insights on op_from and op_to. My understanding is operator is holding the relation of all it's variables in its inputs and outputs. Why we need inverse mapping of the same?
2. Why we should not define 'add_output' like 'add_output_mask', where we won't modify op_from if it is not None?
`    def add_output(self, var):
        if var.op_from is None:
            var.op_from = self
        self.outputs.append(var)
`
3. I ran in 'debug mode' and didn't have any other error except this. Unfortunately, I am not able to share our model and unable to reproduce with some other model. One thing is it is happening while processing 'concat' operator.
  Processing a tf node - model_1/concatenate_2/All
  output: model_1/concatenate_2/All:0

**Comment by buddhapuneeth** [comment]
@wenbingl my issue got resolved by adapting some of the recent changes from the master branch.
('node not in inference_nodeset' check as in https://github.com/onnx/keras-onnx/blob/master/keras2onnx/parser.py#L582)

Still I would like to understand more on the usage of 'op_from' and 'op_to' (i.e., q1 and q2 of my previous question)

**Comment by wenbingl** [comment]
In ONNX, the tensor is independent from the operator, to make the coder easily, we add the op refs in the variable/tensor.
Naturally, a tensor either passed by input or is to be an output of op, so it only can has one input and op_to is single.
And a tensor could be used into the multiply following operator, so the op_to is a list.

**Comment by buddhapuneeth** [comment]
@wenbingl Thanks for the explanation.

**Comment by 34127chi** [comment]
> @wenbingl my issue got resolved by adapting some of the recent changes from the master branch.
> ('node not in inference_nodeset' check as in https://github.com/onnx/keras-onnx/blob/master/keras2onnx/parser.py#L582)
> 
> Still I would like to understand more on the usage of 'op_from' and 'op_to' (i.e., q1 and q2 of my previous question)

hi, can u explain how to fix this problem? i have the same error  while converting our model.
thanks

**Comment by TPF2017** [comment]
> @wenbingl my issue got resolved by adapting some of the recent changes from the master branch.
> ('node not in inference_nodeset' check as in https://github.com/onnx/keras-onnx/blob/master/keras2onnx/parser.py#L582)
> 
> Still I would like to understand more on the usage of 'op_from' and 'op_to' (i.e., q1 and q2 of my previous question)

hi, can u explain how to fix this problem? i have the same error while converting my model.
thanks
