### ISSUE TITLE
Any plans to release 1.7.0 soon?

### ISSUE THREAD

**Issue by anmour90** [onnx/keras-onnx#485]
Hi guys, I need `keras2onnx` desperately to convert `tf2.keras` for my project. The latest tag `1.6.5` won't work for the model I am using and I have to install from the latest master, which is `1.7.0`, but it is not available in the tags. Just wondering when do you guys plan to release `1.7.0`? Thank you!

**Comment by wenbingl** [comment]
We plan a 1.7.0 in the several weeks to support the latest onnx 1.7. But there is no exact date yet

**Comment by jiafatom** [comment]
1.7.0 just got released, thanks for your patience.
