### ISSUE TITLE
type ArgMax cannot be converted

### ISSUE THREAD

**Issue by zhucheng725** [onnx/keras-onnx#487]
Hi , I meet a problem that my network has  an ArgMax operation what code is 
```
x = keras.layers.Lambda(lambda x : tf.argmax(x, axis = 3,output_type=tf.float32))(x)
```
and 
meet this problem:
```
node lambda_1/ArgMax of type ArgMax cannot be converted, fall back to tf2onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhu/keras-onnx-1.6.5/keras2onnx/main.py", line 60, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/home/zhu/keras-onnx-1.6.5/keras2onnx/parser.py", line 794, in parse_graph
    graph, keras_node_dict, topo, top_level, output_names)
  File "/home/zhu/keras-onnx-1.6.5/keras2onnx/parser.py", line 595, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "/home/zhu/keras-onnx-1.6.5/keras2onnx/parser.py", line 335, in _on_parsing_tf_subgraph
    raise RuntimeError("Some tensorflow operation doesn't support, stop converting.")
RuntimeError: Some tensorflow operation doesn't support, stop converting.
```
How to solve this problem.
My keras is 2.1.5 keras-onnx-1.6.5 onnxruntime-1.7.0 tensorflow-1.14.0

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/488), which should work for your case. Please pull keras2onnx master (not install from pypi) and try. Also please pull onnxconverter-common from master.

In your code you mentioned `output_type=tf.float32)`, seems `argmax` only supports `int32` or `int64`?

you mention `onnxruntime-1.7.0`? should be `onnx-1.7` right? please use `onnx 1.6` before `onnxruntime 1.3` gets released.

**Comment by zhucheng725** [comment]
> Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/488), which should work for your case. Please pull keras2onnx master (not install from pypi) and try. Also please pull onnxconverter-common from master.
> 
> In your code you mentioned `output_type=tf.float32)`, seems `argmax` only supports `int32` or `int64`?
> 
> you mention `onnxruntime-1.7.0`? should be `onnx-1.7` right? please use `onnx 1.6` before `onnxruntime 1.3` gets released.

Thank you very much and I retry one more time and can create a .onnx using the tf.argmax.
