### ISSUE TITLE
Return state of RNN as an output

### ISSUE THREAD

**Issue by srikanthderebail** [onnx/keras-onnx#49]
Hello,

I am trying to convert a keras model that has a simplernn layers, and it also returns the last state in addition to the output of RNN. Here is an example:
input = Input(shape=(1,2))
state_in = Input(shape=(10,))
hidden_1, state_out = SimpleRNN(10, activation='relu',return_sequences=True,return_state=True)(input,initial_state=[state_in])
output = Dense(2, activation='linear')(hidden_1)
model = Model(inputs=[input,state_in],outputs=[output,state_out])

The model is converted to onnx without any errors. However, when I look at the onnx file using netron, the state_out is represented as a disconnected node 'simple_rnn_exit_3_0'. I had the impression that return state (last output value of the hidden state) is usually denoted by 'Y_h' which is an optional output in the standard onnx definition of 'rnn'. 

It would be helpful if someone could clarify this issue.

**Comment by jiafatom** [comment]
@srikanthderebail  Thanks, just checked in the [fix](https://github.com/onnx/keras-onnx/commit/726196c868c03ffd4a04cadee24174ec2ba4573f) and it works for me, please try again, thank you!

**Comment by srikanthderebail** [comment]
Works like a charm! Thanks a lot.
