### ISSUE TITLE
optimizing an ONNX model - from tensorflow.keras - error: kernel is undefined

### ISSUE THREAD

**Issue by tompfeil** [onnx/keras-onnx#502]
Trying to optimize this simple model:

```
from tensorflow import keras
import keras2onnx
from onnx.shape_inference import infer_shapes
from onnx.optimizer import optimize

model = keras.Sequential([
    keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    keras.layers.GlobalAveragePooling2D(),
    keras.layers.Dense(10)])

model = keras2onnx.convert_keras(model)
model = infer_shapes(model)
model = optimize(model)
```

results in the following error:

```
File ".../lib/python3.7/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input conv2d/kernel:0 is undefined!
```

I am using tensorflow=2.1.0, onnx=1.7.0, and keras2onnx=1.6.1.

Any ideas how to fix this issue?

I also posted this on stackoverflow: https://stackoverflow.com/questions/62069791/optimizing-an-onnx-model-from-tensorflow-keras-error-kernel-is-undefined

**Comment by jiafatom** [comment]
To support onnx 1.7.0, you need pull keras2onnx from latest master right now (also latest onnxconverter-common), or wait for keras2onnx release which will happen soon.
No need to call `optimize`, keras2onnx has its own optimizer which is better than the `onnx.optimizer`.

**Comment by jiafatom** [comment]
Closing this -- `onnx.optimize` is out of scope for this repo, and keras2onnx has its own optimizer, no need use `onnx.optimize`.

**Comment by bmistral** [comment]
I have the same issue trying to change my model opset (ResNet50 from opset 11 to 8 for my mxnet). Are you sure that the bug comes from the optimize function ?

**Comment by jiafatom** [comment]
optimize function is in onnx repo which is out of scope. If keras2onnx conversion works well, then the bug comes from optimize function. Like mentioned above, keras2onnx has its own optimizer which are better than the optimize function.

**Comment by jay-karan** [comment]
@jiafatom May I ask how keras2onnx's optimizers are different from onnx.optimize?

**Comment by jiafatom** [comment]
keras2onnx optimizer is from `onnxconverter-common`. In addition to `onnx.optimize`, we do many further optimizations to remove `Transpose` ops and similar subgraphs, also other optimizations, as much as we can.

**Comment by jay-karan** [comment]
Thanks @jiafatom 
May you help me in understanding the following-
1. Are there any common optimizers in onnx.optimize and onnxconverter-common?
2. What all frameworks does optimizer from onnxconverter-common support besides keras?
3. Does these optimizations happen on onnx nodes after conversion from source framework?
