### ISSUE TITLE
converting Relu6 

### ISSUE THREAD

**Issue by ShiraLightricks** [onnx/keras-onnx#505]
Hello,
I'm trying to convert my keras model to onnx, using keras2oonx.
python=3.7, keras2onnx=1.7, tensorflow=2.2.0, onnx=1.5

I get this warning:
WARN: No corresponding ONNX op matches the tf.op node model/up_5_block_3X3.2/Relu6 of type Relu6
The generated ONNX model needs run with the custom op supports.

I saw that this issue with the relu6 was resolved in the keras2onnx version 1.6.5 in the file: keras2onnx.ke2onnx.activations,
but when I run the code I see it doesn't use this function, and I didn't find an explanation on how to use it, or how to implement my own custom convert.
Thanks!
Shira

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/506), please pull latest keras2onnx master and onnxconverter-common master and try again.

**Comment by ShiraLightricks** [comment]
Hi,
Thanks for the quick answer, it worked but after I changed something in keras2onnx._builtin.py:
in the function "convert_tf_relu6" raw_operator didn't have an attribute "input", it had "inputs" (or "inputs_dtype" which is a list) and I changed to:
dtype=operator.raw_operator.inputs[0].dtype.as_numpy_dtype

Also I just want to ask about the keras2onnx.ke2onnx.activations.py file - I don't see where in the code it is used or how.
Thank you!
Shira

**Comment by jiafatom** [comment]
Could you provide a simple example to cover your usage, so we can include it in our unit test?

For `keras2onnx.ke2onnx.activations.py`, it has `activation_map` which maps the activation op to the conversion function. It also has the conversion function `convert_keras_activation` to convert keras activation layer, which will be globally registered to convert keras layers. Search for these in our code base, and you will find usage.

Previously we only handle keras layer relu6 activation but not tf.nn.relu6, now we added it per your issue.

**Comment by ShiraLightricks** [comment]
I'm not sure how to give a simple example, 
I have a very complex network and I use the Relu6 in several layers, but thanks for the fix!
