### ISSUE TITLE
No corresponding ONNX op matches type FloorMod,MaxPool,FloorMod

### ISSUE THREAD

**Issue by livecle** [onnx/keras-onnx#516]
When I use keras-onnx to convert centernet(Keras Implementation <a href="https://github.com/xuannianz/keras-CenterNet">keras-CenterNet</a>)

the console outputs some warnings:

```
tf executing eager_mode: True
tf.keras model eager_mode: False
WARN: No corresponding ONNX op matches the tf.op node lambda/mod_1 of type FloorMod
      The generated ONNX model needs run with the custom op supports.
WARN: No corresponding ONNX op matches the tf.op node lambda/MaxPool2d of type MaxPool
      The generated ONNX model needs run with the custom op supports.
WARN: No corresponding ONNX op matches the tf.op node lambda/mod of type FloorMod
      The generated ONNX model needs run with the custom op supports.
The ONNX operator number change on the optimization: 584 -> 189
```

Could someone give me some hints? How to fix these warnings？

Thanks！

**Comment by jiafatom** [comment]
Need support these tf op conversion in `_builtin.py`. Contributions are welcome.

**Comment by jiafatom** [comment]
Both tf ops FloorMod and MaxPool has been supported, please pull latest keras2onnx master branch and try again.

**Comment by livecle** [comment]
Thanks for your work，these warnings have disappeared.
