### ISSUE TITLE
ImportError: cannot import name 'apply_relu_6'

### ISSUE THREAD

**Issue by alexcruz0202** [onnx/keras-onnx#518]
Hello, developers.
I have installed latest version of keras2onnx and onnxconvert-common.
Both of them are `1.7.0`.
When I import the `keras2onnx` module, the following error occurs.

`ImportError: cannot import name 'apply_relu_6'`

Thanks for your latest version.

**Comment by jiafatom** [comment]
Can you make sure that your installed onnxconverter-common points to 1.7.0? `apply_relu_6` is in onnxconverter-common [here](https://github.com/microsoft/onnxconverter-common/blob/96ff60b9acc18242f9b90303c9ca6324394a1e44/onnxconverter_common/onnx_ops.py#L772). We test relu6 in our unit test every day and seems there is no issue about that.

**Comment by alexcruz0202** [comment]
Sorry, there was problem with the old version of onnxconvert-common `1.6.1`.
Thanks in advance.
