### ISSUE TITLE
Tensorflow Keras Conv3D op support

### ISSUE THREAD

**Issue by capaths** [onnx/keras-onnx#521]
Hello,

We've been testing the conversion of a Tensorflow Keras model with a custom layer and some 3D convolution and 3D Average Pooling layers to ONNX using the master branch version of keras2onnx, but the following warnings are shown:

```
WARN: No corresponding ONNX op matches the tf.op node Umonna_Unit_LST_LSTCam/conv3d_8/Conv3D of type Conv3D
      The generated ONNX model needs run with the custom op supports.
WARN: No corresponding ONNX op matches the tf.op node Umonna_Unit_LST_LSTCam/average_pooling3d_3/AvgPool3D of type AvgPool3D
      The generated ONNX model needs run with the custom op supports.
```

Will Tensorflow Conv3D and AvgPool3D ops be supported anytime soon? Or maybe, is there any workaround to this problem?

Thanks!

**Comment by andevellicus** [comment]
+1

**Comment by jiafatom** [comment]
I am afraid that Conv3D and AvgPool3D ops are not supported in near future. It seems to me that onnx Conv op is designed for 1D or 2D, not for 3D.

**Comment by liob** [comment]
After reading the [operator schemas] documentaton, I get the impression that [ONNX supports n-dimensional convs][operator schemas conv]:
> Input data tensor from previous layer; has size (N x C x H x W), where N is the batch size, C is the number of channels, and H and W are the height and width. Note that this is for the 2D image. Otherwise the size is (N x C x D1 x D2 ... x Dn).

I would also appreciate Conv3D and AvgPool3D support.

[operator schemas]: https://github.com/onnx/onnx/blob/master/docs/Operators.md
[operator schemas conv]: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv

**Comment by liob** [comment]
> 
> 
> After reading the [operator schemas](https://github.com/onnx/onnx/blob/master/docs/Operators.md) documentaton, I get the impression that [ONNX supports n-dimensional convs](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv):
> 
> > Input data tensor from previous layer; has size (N x C x H x W), where N is the batch size, C is the number of channels, and H and W are the height and width. Note that this is for the 2D image. Otherwise the size is (N x C x D1 x D2 ... x Dn).
> 
> I would also appreciate Conv3D and AvgPool3D support.

in an effort to not appear insane: there was a comment, which indicated that ONNX does only support 1D and 2D operations. Lesson learned, use the reply function ...

**Comment by jiafatom** [comment]
Just checked in Conv3D [support](https://github.com/onnx/keras-onnx/pull/533), please pull latest keras2onnx master and try.
Not sure if I have time do AvgPool3D soon, can you write model using keras layer?

**Comment by liob** [comment]
Keras-onnx now converts a model with conv3d and avgpooling3d successfully. The results appear to be correct.

@jiafatom thank you very much!
