### ISSUE TITLE
add_node vs apply_op_with_output

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/keras-onnx#522]
1. I am trying to add a new operator, why shouldn't I just add add_node(..) at the end of the converter_funcs.
For example in the below code why can't I just use add_node?
https://github.com/onnx/keras-onnx/blob/master/keras2onnx/_builtin.py#L314
2. Also, I noticed that when we use apply_op_with_output with operators like 'ReverseSequence' like:
oopb.apply_op_with_output('ReverseSequence' ...), it will throw error. So in that case, I need to add additional identity operator at the end. Is there any way I can avoid additional identity operator?

**Comment by jiafatom** [comment]
`apply_op_with_output` calls `apply_X` in `onnxconverter-common` [repo](https://github.com/microsoft/onnxconverter-common). This `apply_X` may need do some extra handling compared to a simple `add_node`. This is why we should always use `apply_op_with_output`.

When you write `oopb.apply_op_with_output('ReverseSequence' ...)`, you need have this 'ReverseSequence' available in `onnxconverter-common`. Once that is done, you don't need additional identity.
