### ISSUE TITLE
TF 2.2 sequential GRU layer conversion doesn't work

### ISSUE THREAD

**Issue by vishakg** [onnx/keras-onnx#526]
I have a simple example that fails to convert:

```
model = tf.keras.Sequential(name='TestGRU')
model.add(tf.keras.layers.GRU(400, reset_after=True))
model.add(tf.keras.layers.Dense(257, activation='sigmoid'))

model.build(input_shape=(1, 1, 257))
model.compile(optimizer='adam', loss='mse')

x = np.zeros((32,1,257))
y = np.zeros((32, 1, 257))

model.fit(x,y)

onnx_model = keras2onnx.convert_keras(model, name=model.name)

```

I get this error:

> Traceback (most recent call last):
>   File ".\test.py", line 53, in <module>
>     onnx_model = keras2onnx.convert_keras(model, name=model.name)
>   File "C:\Users\user\Source\Repos\speech\tensorflow2\lib\site-packages\keras2onnx\main.py", line 62, in convert_keras
>     tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)
>   File "C:\Users\user\Source\Repos\speech\tensorflow2\lib\site-packages\keras2onnx\_parser_tf.py", line 304, in build_layer_output_from_model
>     graph = model.outputs[0].graph
> TypeError: 'NoneType' object is not subscriptable

I even tried with a subclass approach:
```
class TstGru(tf.keras.models.Model):
    def __init__(self):
        super(TstGru, self).__init__()
        self.gru_2 = tf.keras.layers.GRU(400)
        self.fc_out = tf.keras.layers.Dense(257, activation='sigmoid')

    def call(self, input):
        out = self.gru_2(input)
        out = self.fc_out(out)

        return out

model = TstGru()
```

This gives a placholder error as follows:

> ValueError: Cannot find the Placeholder op that is an input to the ReadVariableOp.

**Comment by jiafatom** [comment]
Just checked in the fix above. The sequential model should work now. You need specify `input shape` in the model. see the [PR](https://github.com/onnx/keras-onnx/pull/528) you can find the example.

**Comment by vishakg** [comment]
Thanks for the fix!
