### ISSUE TITLE
When converted on macOS, it exits with `libprotobuf ERROR`.

### ISSUE THREAD

**Issue by yuto51942** [onnx/keras-onnx#531]
Hello.

I am trying to convert an h5 file to onnx on MacOS. But every time I get a libprotobuf ERROR and I can't convert it.
Is there a solution to this error?

When I ran it on Ubuntu 18.04, it worked fine and I was able to convert it.

## environment

- OS: MacOS Catalina version:10.15.5
- Python==3.6.10
- Tensorflow==2.1.0
- keras2onnx == 1.7.0 (from github)
- onnxconverter-common==1.7.0 (from github)

## scripts and log

model:

```python
import tensorflow as tf


def main():
    model = tf.keras.applications.MobileNetV2()
    model.save('model.h5')

if __name__ == "__main__":
    main()
```

convert:

```python
import os

import keras2onnx
import tensorflow as tf


def convert():
    keras_model_path = os.path.join('original_model', 'model.h5')
    onnx_model_path = os.path.join('onnx_model', 'model.onnx')

    model = tf.keras.models.load_model(keras_model_path)
    onnx_model = keras2onnx.convert_keras(model)
    keras2onnx.save_model(onnx_model, onnx_model_path)


if __name__ == "__main__":
    convert()
```

execution Log:

```bash
$ python convert.py

[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
[1]    95132 abort      python convert.py
```

**Comment by jiafatom** [comment]
Is this bug in `load_model` or `convert_keras`?

**Comment by yuto51942** [comment]
@jiafatom 
There seems to be no error with `load_model`. The error occurs at the time of importing `keras2onnx`.

**Comment by Peter1234444** [comment]
I'm getting the same problem. Everything works fine when I run a script with only the following: 

```
import onnx
import keras2onnx
```

But when I run a script that fits a keras model, I get this error when python tries to execute the line 

`import keras2onnx `

Output after running above line after fitting model: 
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
zsh: abort      python test_model.py
```

I'm getting the feeling this might be a memory problem related after briefly skimming over other forums... potentially something to do with CUDA and Mac OS. I was getting other errors from my Jupyter Notebook on trying to execute the same line (import keras2onnx). See https://github.com/tensorflow/tensorflow/issues/9829

**Comment by tdp2110** [comment]
Same issue here. `python -c 'import keras; import keras2onnx'` is enough to give the above error.

Keras 2.4.3
TensorFlow 2.3.0
Keras2Onnx 1.7.0
MacOS Catalin 10.15.6
Python 3.7.7

In my case, I gave up on MacOS and moved to Linux where things worked just fine ¯\_(ツ)_/¯

**Comment by wenbingl** [comment]
This seems to be an ONNX package that the converter depends on, please check the related issue here:
https://github.com/onnx/onnx/issues/2940,

**Comment by yuto51942** [comment]
@wenbingl 
Thank you. I was able to convert it well!
