### ISSUE TITLE
Dev question: Graph transformation at runtime 

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/keras-onnx#535]
This is not a bug, this is a dev question:
Say, I added a new operator OpA (tf operator) in __builtin.py like
```
#opA is not an ONNX operator, 
@converter_func(TYPES.OpA)
def convert_tf_opA(scope, operator, container):
    # do manipulation on node inputs and finally calling standard ONNX operator like identity 
    oopb.apply_op_with_output('apply_identity', [ip], operator.outputs, name=node.name + '_Identity')
```

Now adding another new operator, opB (tf operator):
```
#opB is not an ONNX operator, 
@converter_func(TYPES.OpB)
def convert_tf_opB(scope, operator, container):
    # do manipulation on node inputs and finally calling opA which is created above
    container.add_node('OpA', opA_input,  operator.outputs, name=_name('opB'))
```

For an input graph with OpB, I am expecting it to have an 'Identity' operator in final ONNX graph (after graph transformation like: opB to opA to Identity)

But currently instead I'm getting opA in the final ONNX graph, as opA is also an TF operator, I am not able to run on ONNXRuntime. Instead I want to have 'identity' here.
Is there a way to achieve this?

**Comment by wenbingl** [comment]
Not sure if I got your point, what you need is to avoid the 'identify' node being removed during the model optimization?

**Comment by buddhapuneeth** [comment]
Sorry for the confusion. I am able to fix the issue. In brief, we can do container.add_node(...) for ONNX standard operators.

For others let me explain my scenario again,  suppose I have 2 non-ONNX operators (some TF operators). I want to transform them to ONNX operators. In __buildin.py, I added code for opA to some standard ONNX operator (Say 'Identity').
opB and opA are kind of related. So added code to convert opB to opA, assuming that in the final graph I can see 'Identity' operator, but instead I am seeing opA itself. 
This is because container.add_node(..) can be used with only standard ONNX operators. To make it work, i replicated the code in opA conversion inside opB conversion as well.
