### ISSUE TITLE
Improper Topological sorting of Nodes in the ONNX model

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/keras-onnx#537]
I am noticing issues with the topological sorting of nodes in the ONNX model. The nodes list is coming in different order than expected. Of course, inference engines like ONNXRuntime can handle nodes in any order. But we have hard requirement on the node order.

I tried to debug around [topology.py](https://github.com/onnx/keras-onnx/blob/master/keras2onnx/topology.py#L256). Yet find the root cause. 

To reproduce
Download keras model from [here](https://drive.google.com/file/d/1E-9H3NXt2Kuu07RjykCq4oeplxTqLX8u/view?usp=sharing)
Do ONNX conversion
Output (in txt) is as below
[negative.txt](https://github.com/onnx/keras-onnx/files/4832863/negative.txt)
 If you visualize the graph, the nodes are in different order than the nodes in the negative.txt.

**Comment by wenbingl** [comment]
This is where the final topo sorting is:

https://github.com/microsoft/onnxconverter-
common/blob/e24784a4ac3839f32ef88956a42f4ecc4814912c/onnxconverter_common/optimizer.py#L1670

**Comment by buddhapuneeth** [comment]
This is solved. When I am running in debug mode, onnxconverter-common optimization wont run. So graph will have unordered list of nodes and additional identity nodes.
