### ISSUE TITLE
Converting RCNN gives error

### ISSUE THREAD

**Issue by MathijsNL** [onnx/keras-onnx#573]
Hello,

Today I have been struggling to get this keras model converted to ONNX.
Python version: 3.7
TF-gpu version: 2.2.0
Keras version: 2.4.3
keras2onnx version: 1.7.0

The trained network I am trying to convert:
[https://github.com/akTwelve/Mask_RCNN](https://github.com/akTwelve/Mask_RCNN)
I can run the netwerk fine, and I am getting all outputs without any errors. Not sure if relevent but the type of network is:
tensorflow.python.keras.engine.training.Model

The code I am using to convert it:
```
import keras2onnx
print("keras2onnx version is "+keras2onnx.__version__)
# convert to onnx model
onnx_model = keras2onnx.convert_keras(model.keras_model, 'test', debug_mode=1)
output_model_path = "test-model.onnx"
# and save the model in ONNX format
keras2onnx.save_model(onnx_model, output_model_path)
```

The error:
```
lib/python3.7/site-packages/keras2onnx/_parser_tf.py in infer_variable_type(tensor, opset, inbound_node_shape)
     46     else:
     47         raise ValueError(
---> 48             "Unable to find out a correct type for tensor type = {} of {}".format(tensor_type, tensor.name))
     49 
     50 

ValueError: Unable to find out a correct type for tensor type = <dtype: 'variant'> of mask_rcnn/mrcnn_detection/map/while/exit/_37:0
```

And the last 15 lines of the keras2onnx debug:
```
Processing a tf node - mask_rcnn/mrcnn_detection/DenseToDenseSetOperation
	output: mask_rcnn/mrcnn_detection/DenseToDenseSetOperation:0
	output: mask_rcnn/mrcnn_detection/DenseToDenseSetOperation:1
	output: mask_rcnn/mrcnn_detection/DenseToDenseSetOperation:2
	input : mask_rcnn/mrcnn_detection/ExpandDims:0
	input : mask_rcnn/mrcnn_detection/ExpandDims_1:0
('mask_rcnn/mrcnn_detection/zeros', 'Custom_Layer')
Processing a tf node - mask_rcnn/mrcnn_detection/zeros
	output: mask_rcnn/mrcnn_detection/zeros:0
('mask_rcnn/mrcnn_detection/map/TensorArrayV2Stack/TensorListStack', 'Custom_Layer')
WARN: No corresponding ONNX op matches the tf.op node mask_rcnn/mrcnn_detection/map/TensorArrayV2Stack/TensorListStack of type TensorListStack
      The generated ONNX model needs run with the custom op supports.
Processing a tf node - mask_rcnn/mrcnn_detection/map/TensorArrayV2Stack/TensorListStack
	output: mask_rcnn/mrcnn_detection/map/TensorArrayV2Stack/TensorListStack:0
	input : mask_rcnn/mrcnn_detection/map/while/exit/_37:0
```

It probably has something to do with the custom op support, but I just cannot find how to solve it. I hope someone here can point me in the right direction.

**Comment by jiafatom** [comment]
The mask rcnn conversion with custom conversion can be found in our nightly build, see [here](https://github.com/onnx/keras-onnx/blob/master/applications/nightly_build/test_mask_rcnn.py).

**Comment by MathijsNL** [comment]
Thanks for the quick reply. This is really the thing I needed. It is working as intended now!

**Comment by danielsernabuitrago** [comment]
Hi @MathijsNL, could you please help me trough of how you solved it, I'm stuck exactly where you were, and I see the code, but there are many things I don't have, where can I get the nightly build ?

**Comment by MathijsNL** [comment]
Take a look at this:

https://github.com/onnx/keras-onnx/tree/master/applications/mask_rcnn

That code is able to convert to ONNX and apply the ONNX model.

Make sure to put the dependencies in the right places.

Let me know if you can work it out with this info.

Op vr 14 aug. 2020 17:24 schreef danielsernabuitrago <
notifications@github.com>:

**Comment by MathijsNL** [comment]
Take a look at this:

https://github.com/onnx/keras-onnx/tree/master/applications/mask_rcnn

That code is able to convert to ONNX and apply the ONNX model.

Make sure to put the dependencies in the right places.

Let me know if you can work it out with this info.

**Comment by danielsernabuitrago** [comment]
Thanks a lot @MathijsNL, it worked !!

**Comment by MathijsNL** [comment]
I didn't do the work though! Credits go to those who wrote the code.

Are you implementing this in C# by any chance?

**Comment by danielsernabuitrago** [comment]
Yeah agree...

No I'm working on python, and on my way to implementing with intel's openvino
