### ISSUE TITLE
Can't convert Conv2d layer in efficientnet; "Unable to find out a correct type for tensor type = 20"

### ISSUE THREAD

**Issue by DavidFromMerlin** [onnx/keras-onnx#579]
Keras Efficientnet models are built into TensorFlow 2.3.0. But when I try to convert the model with keras-onnx, I get:

  File ".\lanes.py", line 287, in output_onnx
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "[...]\Python38\lib\site-packages\keras2onnx\main.py", line 102, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "[...]\Python38\lib\site-packages\keras2onnx\parser.py", line 853, in parse_graph
    return _parse_graph_core_v2(
  File "[...]\Python38\lib\site-packages\keras2onnx\parser.py", line 732, in _parse_graph_core_v2
    on_parsing_keras_layer_v2(graph, layer_info, varset)
  File "[...]\Python38\lib\site-packages\keras2onnx\_parser_tf.py", line 332, in on_parsing_keras_layer_v2
    var_type = adjust_input_batch_size(infer_variable_type(i_, varset.target_opset))
  File "[...]\Python38\lib\site-packages\keras2onnx\_parser_tf.py", line 47, in infer_variable_type
    raise ValueError(
**ValueError: Unable to find out a correct type for tensor type = 20 of top_conv/Conv2D/ReadVariableOp/resource:0**

Doing some debugging, I see that the troublesome tensor looks like this:
>>> pprint(vars(tensor))
{'_consumers': [],
 '_dtype': tf.resource,
 '_id': 8091,
 '_name': 'top_conv/Conv2D/ReadVariableOp/resource:0',
 '_op': <tf.Operation 'top_conv/Conv2D/ReadVariableOp/resource' type=Placeholder>,
 '_shape_val': TensorShape([]),
 '_tf_output': <tensorflow.python._pywrap_tf_session.TF_Output object at 0x000001CB262DF830>,
 '_value_index': 0}

>>> pprint(tensor.op)
<tf.Operation 'top_conv/Conv2D/ReadVariableOp/resource' **type=Placeholder**>

>>> pprint(vars(tensor.op))
{'_c_op': <tensorflow.python._pywrap_tf_session.TF_Operation object at 0x000001CB262DF930>,
 '_colocation_code_locations': {},
 '_control_flow_context': None,
 '_device_code_locations': [],
 '_gradient_function': None,
 '_graph': <tensorflow.python.framework.func_graph.FuncGraph object at 0x000001C9493616A0>,
 '_id_value': 1741,
 '_inputs_val': (),
 '_is_stateful': False,
 '_original_op': None,
 '_outputs': [<tf.Tensor 'top_conv/Conv2D/ReadVariableOp/resource:0' shape=() dtype=resource>],
 '_traceback': <tensorflow.python._tf_stack.StackSummary object at 0x000001CB262DF730>}

>>> pprint(tensor.op.node_def)
name: "top_conv/Conv2D/ReadVariableOp/resource"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_RESOURCE
  }
}
attr {
  key: "shape"
  value {
    shape {
    }
  }
}

Note that the tensor.op.node_def.attr['dtype'] is DT_RESOURCE, which is where the "20" in the error message comes from. (DT_RESOURCE is type 20 in the Tensorflow protobuf)

**Comment by DavidFromMerlin** [comment]
For more info, I am using the latest github source for keras-onnx and the layer that is failing is here in Keras source code: https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/keras/applications/efficientnet.py#L358

**Comment by jiafatom** [comment]
tf 2.3 support is ongoing, please use tf 2.2 at this moment.

**Comment by DavidFromMerlin** [comment]
Thanks, my mistake.
