### ISSUE TITLE
Wrong node order in generated onnx proto

### ISSUE THREAD

**Issue by mnboos** [onnx/keras-onnx#58]
I exported a yolo3 to onnx and reloaded it again. For some debugging, I printed the nodes of the loaded graph to a file:

```python
    with open("yolo3_graph.txt", 'w') as f:
        for n in onnx_model.graph.node:
            f.write(str(n))
            f.write("\n\n")
```

While inspecting the file, I noticed that the order of the node fits to the problem within another library, that I was actually debugging. It claimed, that there is no input `leaky_re_lu_73_LeakyRelu_0` for the node `Transpose3`. If you look at the screenshot below you'll see, that `LeakyRelu` should be defined prior to `Transpose`.

![image](https://user-images.githubusercontent.com/22575883/55708275-cd676900-59e5-11e9-9798-d3818eacb07e.png)

But the order from the printed nodes was actually the other way round (I removed the attributes from each node for the sake of readability:

```
input: "input_2_01"
output: "adjusted_input"
name: "Transpose"
op_type: "Transpose"

input: "adjusted_input"
input: "W"
output: "convolution_output"
name: "conv2d_76"
op_type: "Conv"

input: "convolution_output"
input: "scale"
input: "bias"
input: "mean"
input: "var"
output: "batch_norm_output_buffer"
name: "batch_normalization_73"
op_type: "BatchNormalization"

input: "leaky_re_lu_73_LeakyRelu_0"
output: "batch_normalization_73_cond_Merge_0"
name: "Transpose3"
op_type: "Transpose"

input: "batch_norm_output_buffer"
output: "leaky_re_lu_73_LeakyRelu_0"
name: "leaky_re_lu_73"
op_type: "LeakyRelu"

input: "batch_normalization_73_cond_Merge_0"
output: "TFNodes29_zero_padding2d_6_Pad_0"
name: "TFNodes29_zero_padding2d_6_Pad"
op_type: "Pad"
```

In the [IR docs](https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs) it says

> A list of nodes, forming a partially ordered computation graph based on input/output data dependencies.

Does this mean, that the order of the nodes as resulting from `onnx_model.graph.node` might be incorrect, in which case one would have to first derive the correct order using some graph theory, or that there is an error in the creation of the onnx using `keras2onnx`?

**Comment by jiafatom** [comment]
@mnboos The nodes should be topologically sorted. You mentioned "export a yolo3 to onnx", is it from keras2onnx converter or other converters?  If it is keras2onnx, can you share the script? Thanks.

**Comment by mnboos** [comment]
> is it from keras2onnx converter or other converters?

It's from keras2onnx, which I used like this:

```python
import keras2onnx
import onnxmltools

onnx_model = keras2onnx.convert_keras(self.yolo_model)
onnxmltools.utils.save_model(onnx_model, "/output_dir/yolo.onnx")
```

And here is the onnx model, from which I only kept a few of the first layer in order to reduce the filesize.
[yolo.zip](https://github.com/onnx/keras-onnx/files/3057217/yolo.zip)

**Comment by jiafatom** [comment]
@mnboos keras converter uses onnx.helper.make_graph to make the onnx graph, given the converted onnx nodes. This topology sort should be done in onnx, not in keras converter. I have created an [issue](https://github.com/onnx/onnx/issues/1920) for onnx, and move the future discussion there. So I will close the issue here. Thanks.
