### ISSUE TITLE
ReLU negative slope ignored?

### ISSUE THREAD

**Issue by tdp2110** [onnx/keras-onnx#584]
I've been investigating some divergence between a converted keras model and the original model.
The first layerwise difference I find is at a ReLU layer. My differences (checked with `numpy.testing.assert_allclose`) look like 

```
checking output dense  ... OK!
checking output dense_1  ... OK!
checking output re_lu  ... 
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-07

Mismatched elements: 583 / 1024 (56.9%)
Max absolute difference: 0.01077522
Max relative difference: 1.7480605e-05
 x: array([[ 0.015924, -0.00205 , -0.007421, ..., -0.00298 ,  0.032283,
         0.026983]], dtype=float32)
 y: array([[0.015924, 0.      , 0.      , ..., 0.      , 0.032283, 0.026983]],
```

The `x` arg to `numpy.testing.assert_allclose` is the keras output, the `y` arg is the onnx output, as computed by `onnxruntime`.

The layer has parameters
```
# node properties
  type: ReLU
  name: re_lu
# Attributes
  dtype: float32
  negative_slope: 0.1
  threshold: 0
  trainable: true
# inputs
  input name: dense_1
# outputs
  output: name: re_lu
```

Given the zeros in the onnx output, my guess is either the converter is ignoring the negative slope or the `onnxruntime` is. I suspect the issue is with the converter because this layer maps to a `Clip`. Using a different inference framework, TensorRT, I also find the zeros.

**Comment by jiafatom** [comment]
Can you provide a simple script for us to debug? thanks!

**Comment by tdp2110** [comment]
@jiafatom thanks for the response. I'll try to whip something up. Shouldn't be too hard.

**Comment by tdp2110** [comment]
I think this should run without triggering an assert, but it doesn't for me. Note that it does pass if there's no negative slope on the `ReLU`.

```
from keras.layers import ReLU, Input
from keras.models import Sequential

import keras2onnx
import onnxruntime

import numpy as np
import numpy.testing


model_input = np.array([-2, -1, -0.1, -0.5, 0, 1, 2],
                       dtype=np.float32)
negative_slope = 0.1

keras_model = Sequential()
keras_model.add(Input(shape=model_input.shape))
keras_model.add(ReLU(negative_slope=negative_slope))

keras_result = keras_model.predict(model_input).ravel()

onnx_model = keras2onnx.convert_keras(keras_model)

content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
feed = {'input_1': model_input.reshape(1, -1)}
onnx_result = np.array(sess.run(None, feed)).ravel()

numpy.testing.assert_allclose(keras_result, onnx_result)
```

In case it matters, here are some version numbers I'm working with:

```
keras2onnx==1.7.0
keras==2.4.3
tensorflow==2.3.0
onnxruntime==1.4.0
```

**Comment by tdp2110** [comment]
FYI, in my original example, not the small repro shared above, I manually edited your generated onnx model to hold LeakyRelu instead of Clip and it seems to do the right thing now (but the converter got me 95% of the way there 😄).

**Comment by jiafatom** [comment]
Made a fix and checked in [here](https://github.com/onnx/keras-onnx/pull/585), please pull keras2onnx master and retry.

**Comment by tdp2110** [comment]
Pulled master and it works great! This is by far the fastest turnaround I've ever experienced on a bug report, open source or otherwise. Thank you for your efforts! 👍
