### ISSUE TITLE
when i tried to use keras.backend.scatter_nd got different types (tensor(int64) and tensor(float) in nodedifferent types (tensor(int64) and tensor(float) in node error

### ISSUE THREAD

**Issue by netilovefm1** [onnx/keras-onnx#623]
keras requires to me use index int32 or int64 type but onnx said like that

so how can I use scatter_nd in keras layer;;;;....

**Comment by jiafatom** [comment]
We recently have a fix on scatter_nd and should fix this issue. Please pull keras2onnx master and retry.

**Comment by netilovefm1** [comment]
thanks to reply i hope it will can soon

**Comment by jiafatom** [comment]
It is already working now. Just pull keras2onnx master and try it.

**Comment by netilovefm1** [comment]
what do u mean? 

pull keras2onnx master? 

I don't understand what u mean

**Comment by jiafatom** [comment]
Please check Readme about installing from source:
`pip install -U git+https://github.com/onnx/keras-onnx`

**Comment by netilovefm1** [comment]
thanks to answer ^^
