### ISSUE TITLE
How to convert a keras model with custom activation to ONNNX

### ISSUE THREAD

**Issue by abhi-shirk** [onnx/keras-onnx#631]
I am trying to convert a keras biLSTM model to ONNX.

def gelu(x):
    cdf = 0.5 * (1.0 + tf.tanh(
      (np.sqrt(2 / np.pi) * (x + 0.044715 * tf.pow(x, 3)))))
    return x * cdf

modelfile = "./model-stage-3.h5"
model = tf.keras.models.load_model(modelfile,custom_objects = {"gelu": gelu})
print(model.summary())

_Layer (type)                 Output Shape              Param #   
=================================================================
input (InputLayer)           [(None, 20)]              0         
_________________________________________________________________
word_embedding (Embedding)   (None, 20, 300)           9585600   
_________________________________________________________________
dropout_2 (Dropout)          (None, 20, 300)           0         
_________________________________________________________________
bilstm (Bidirectional)       (None, 20, 1200)          4324800   
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 1200)              0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 1200)              0         
_________________________________________________________________
dense (Dense)                (None, 768)               922368    
_________________________________________________________________
dropout_4 (Dropout)          (None, 768)               0         
_________________________________________________________________
output (Dense)               (None, 2)                 1538      
=================================================================
Total params: 14,834,306
Trainable params: 14,834,306
Non-trainable params: 0
__________________________________________________________________

import os
os.environ['TF_KERAS'] = '1'
import onnx
import keras2onnx

onnx_model = keras2onnx.convert_keras(model, model.name)

Error:
 ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-9f084ca2714f> in <module>
----> 1 onnx_model = keras2onnx.convert_keras(model, model.name)

~\AppData\Local\Continuum\anaconda3\envs\pyto\lib\site-packages\keras2onnx\main.py in convert_keras(model, name, doc_string, target_opset, channel_first_inputs, debug_mode, custom_op_conversions)
     81     topology.compile()
     82 
---> 83     return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
     84 
     85 

~\AppData\Local\Continuum\anaconda3\envs\pyto\lib\site-packages\keras2onnx\topology.py in convert_topology(topology, model_name, doc_string, target_opset, channel_first_inputs)
    320         if cvt is None:
    321             raise RuntimeError("Unexpected error on find the converter for op {}".format(operator.type))
--> 322         cvt(scope, operator, container)
    323 
    324     # enable the ONNX optimizations

~\AppData\Local\Continuum\anaconda3\envs\pyto\lib\site-packages\keras2onnx\ke2onnx\dense.py in convert_keras_dense(scope, operator, container)
     41               axis=-1, broadcast=1)
     42 
---> 43     activation_process(scope, operator, container, biased_tensor_name)

~\AppData\Local\Continuum\anaconda3\envs\pyto\lib\site-packages\keras2onnx\ke2onnx\common.py in activation_process(scope, operator, container, biased_tensor_name)
     22 def activation_process(scope, operator, container, biased_tensor_name):
     23     # Create an activation function node and apply activation function to the intermediate tensor
---> 24     apply_activation_function = activation_map[operator.raw_operator.activation]
     25     if operator.raw_operator.activation in [activation_get('softmax'), keras.activations.softmax]:
     26         apply_softmax(scope, biased_tensor_name, operator.outputs[0].full_name, container, axis=-1)

KeyError: <function gelu at 0x0000023F592A9158>

**Comment by jiafatom** [comment]
Here is an example to use custom relu6, see [here](https://github.com/onnx/keras-onnx/blob/0c037e5968c0b5dc6bb12dcf4edcfdeeaf4c964f/applications/nightly_build/test_semantic_segmentation.py#L1192). Can you do something similar?

**Comment by abhi-shirk** [comment]
Do we have to do it while preparation of the model before training??

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/632), please use custom activation as an Activation layer, and pull keras2onnx master and retry.
