### ISSUE TITLE
keras2onnx is not working for LSTM with return_sequences = True. 

### ISSUE THREAD

**Issue by ragvri** [onnx/keras-onnx#639]
I'm trying to train a simple model using TF 2.0

```
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.LSTM(32,
                                          return_sequences=True,
                                          input_shape=x_train_multi.shape[-2:]))
model.add(tf.keras.layers.LSTM(16, activation='tanh'))
model.add(tf.keras.layers.Dense(72))

model.compile(optimizer=tf.keras.optimizers.RMSprop(clipvalue=1.0), loss='mae')
```

The model trains fine but when I try to convert it to onnx model using the following

```
import os
    os.environ['TF_KERAS'] = '1'
    from keras2onnx import convert_keras
    onnx_model = convert_keras(model, 'my_model2.onnx')
    # Save model to local .onnx file
    with open("./my_model.onnx", "wb") as f:
        f.write(onnx_model.SerializeToString())
```

I get an error saying that `lstm/PartitionedCall:1 is disconnected, check the parsing log for more details.`.

If I train the same model with return sequences as False, then the model works perfectly. Can anyone please help me? 

My env: 

```
keras2onnx = 1.7.0
tensorflow = 2.3.0
```

**Comment by jiafatom** [comment]
We have a recent fix for this. Please pull keras2onnx master (see Readme) and retry.

**Comment by ragvri** [comment]
Wow, it works after updating keras2onnx to `1.7.1`, thanks.

**Comment by l2009312042** [comment]
keras2onnx  1.7.1  is not exist, how to update keras2onnx?
