### ISSUE TITLE
[ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model

### ISSUE THREAD

**Issue by vss96** [onnx/keras-onnx#670]
I have been trying to convert the keras version of Yolov3 into onnx. The conversion happens without any error but when i run the model the Invalid graph error pops up.

`Traceback (most recent call last):
  File "predict_onnx.py", line 107, in <module>
    onnx_boxes = get_onnx_boxes(image, 608, 608, anchors, 0.5, 0.45)
  File "predict_onnx.py", line 48, in get_onnx_boxes
    tf_output = run_onnx(image_data)
  File "predict_onnx.py", line 20, in run_onnx
    sess = onnxruntime.InferenceSession('nike_redbull.onnx')
  File "/Users/vikass/Documents/wink-yolo/yolo-gpu/winkenv/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/Users/vikass/Documents/wink-yolo/yolo-gpu/winkenv/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:TFNodes30_zero_padding2d_1_Pad : Node (TFNodes30_zero_padding2d_1_Pad) has input size 1 not in range [min=2, max=3].`
I noticed in other issues where they used target opset as 10 to make the model work. It did work but I'm getting other junk boxes along with the correct box as well. Any idea on what the issue might be?

**Comment by jiafatom** [comment]
For yolov3 conversion, see the example [here](https://github.com/onnx/keras-onnx/blob/master/applications/nightly_build/test_yolov3.py) which runs well in our nightly build daily.

**Comment by vss96** [comment]
Thanks
