### ISSUE TITLE
onnxruntime can not load onnx from keras2onnx

### ISSUE THREAD

**Issue by wkt** [onnx/keras-onnx#680]
The code:
`
import numpy as np
from tensorflow.python.keras import Input, Model
from tensorflow.python.keras.layers import Conv2D, GlobalAveragePooling2D, Dense, Multiply, add
import onnxruntime
import os

os.environ['TF_KERAS'] = "1"
import keras2onnx

def build_model(inputs):
    _input = Input(inputs, dtype='float32')
    x = Conv2D(32, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(_input)
    temp = GlobalAveragePooling2D()(x)
    temp = Dense(int(x.shape[-1]), use_bias=False)(temp)
    temp = Dense(int(temp.shape[-1]), use_bias=False, activation='relu')(temp)
    temp = Multiply()([x, temp])
    x = add([x, temp])
    return Model(inputs=_input, outputs=x)

img_size = 224
img = np.random.randint(0, 255, (img_size, img_size, 3)).astype('float32')/127.0-1.

model = build_model(inputs=(img_size, img_size, 3))
model.summary()

onnx_model = keras2onnx.convert_keras(model, model.name, **debug_mode=False**)

imgs = np.asarray([img])
pred_keas = model.predict(imgs)

# runtime prediction
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
feed = {sess.get_inputs()[0].name: imgs}

pred_onnx = sess.run(None, feed)
print("pred_onnx:", pred_onnx[0].shape)
print("pred_keas:", pred_keas.shape)
print("sum:", np.sum(np.square(pred_onnx[0] - pred_keas)))
`
error:
`Traceback (most recent call last):
  File "tests/test_keras2onnx1.py", line 45, in <module>
    sess = onnxruntime.InferenceSession(content)
  File "~/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "~/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (PushTranspose_0) Op (Transpose) [TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {0, 32}
`
Versions:
tensorflow-gpu: 1.13.2
keras2onnx: 1.7.0
onnxruntime: 1.6.0
onnxconverter-common: 1.7.0

And :
    onnx_model = keras2onnx.convert_keras(model, model.name, **debug_mode=True**)
    will fix it for now.

**Comment by jiafatom** [comment]
Please try keras2onnx and onnxconverter-common from master branch.

**Comment by wkt** [comment]
> Please try keras2onnx and onnxconverter-common from master branch.

Use onnxconverter-common from master branch will fix
thank
