### ISSUE TITLE
Failed to read converted model

### ISSUE THREAD

**Issue by mikhail-barg** [onnx/keras-onnx#77]
I'm trying to convert and use a Keras model from [Russtres](https://github.com/MashaPo/russtress/tree/master/russtress):

```python
from keras.models import model_from_json
import keras2onnx
import onnx
import onnxruntime

with open('/home/user/russtress/dev/russtress/russtress/text_model.json', 'r') as content_file:
	json_string = content_file.read()
model = model_from_json(json_string)
model.load_weights('/home/user/russtress/dev/russtress/russtress/weights.96.hdf5')

onnx_model = keras2onnx.convert_keras(model, model.name)
onnx.save_model(onnx_model, '/home/user/russtress/dev/model.onnx')

sess = onnxruntime.InferenceSession( '/home/user/russtress/dev/model.onnx')
```

which gives me 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/russtress/env/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from /home/user/russtress/dev/model.onnx failed:[TypeInferenceError] Invalid attribute perm {2, 0, 1, 3}, input shape = {2, 1, 64}
```

I'm using [latest](https://github.com/onnx/keras-onnx/commit/eca3cf302812a38c23137f60469d781c0918a9f4) keras2onnx from this repo. 

The model in Netron looks like this:
![image](https://user-images.githubusercontent.com/2208971/57136308-17f5be80-6db5-11e9-934d-bebef04f1a89.png)

The problem looks like [this one](https://github.com/onnx/onnxmltools/issues/138) which is marked as resolved.

Converted model: [model.onnx.zip](https://github.com/onnx/keras-onnx/files/3142878/model.onnx.zip)

**Comment by jiafatom** [comment]
@mikhail-barg your input shape should be 4 dimension, but {2, 1, 64} is 3d, did you add the batch dimension?

**Comment by BalievDmitri** [comment]
> @mikhail-barg your input shape should be 4 dimension, but {2, 1, 64} is 3d, did you add the batch dimension?

This error happens on line
 sess = onnxruntime.InferenceSession( '/home/user/russtress/dev/model.onnx')
So there is no input to to the network here.

**Comment by mikhail-barg** [comment]
> @mikhail-barg your input shape should be 4 dimension, but {2, 1, 64} is 3d, did you add the batch dimension?

As @BalievDmitri  already wrote, I haven't yet get to inference, only tried to load the model, so I'm not sure if there's anything I could do regarding input shape. Could you please elaborate on what exactly should I do here?

**Comment by jiafatom** [comment]
@BalievDmitri @mikhail-barg Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/85), please check if it works.

**Comment by alextrosta** [comment]
Hey @jiafatom,
I've ran into a similar issue as @mikhail-barg.
i.e. 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-9753755dee63> in <module>
      1 content = onnx_model.SerializeToString()
----> 2 sess = rt.InferenceSession(content)

/anaconda3/envs/onnx/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options)
     29             self._sess.load_model(path_or_bytes)
     30         elif isinstance(path_or_bytes, bytes):
---> 31             self._sess.read_bytes(path_or_bytes)
     32         elif isinstance(path_or_bytes, tuple):
     33             # to remove, hidden trick

RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : [TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {1, 3, 64}
```
Here is my `model.summary()`:
```
________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1d_1 (Conv1D)            (None, 3, 64)             10432     
_________________________________________________________________
batch_normalization_1 (Batch (None, 3, 64)             256       
_________________________________________________________________
flatten_1 (Flatten)          (None, 192)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                3088      
_________________________________________________________________
batch_normalization_2 (Batch (None, 16)                64        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
=================================================================
Total params: 13,857
Trainable params: 13,697
Non-trainable params: 160
_________________________________________________________________
```
Following the advice in https://github.com/onnx/onnxmltools/issues/138#issuecomment-461203500, 
I tried the following:
```
onnx_model = keras2onnx.convert_keras(model, "model4")
onnx.save_model(onnx_model, 'model4.onnx')
content = onnx_model.SerializeToString()
sess = rt.InferenceSession(content)
```
which produces the `RuntimeError` shown above. 

I should mention that I've `pip install git+https://github.com/onnx/keras-onnx` and `keras2onnx/ke2onnx` contains the changes you've committed in https://github.com/onnx/keras-onnx/commit/77629e8a1d73056d0b6f2265c85f3197d4470660.

Any help would be appreciated.

**Comment by jiafatom** [comment]
@alextrosta please open a new issue for this, because this is nothing to do with Bidirectional wrapper.

**Comment by alextrosta** [comment]
Sure @jiafatom --> https://github.com/onnx/keras-onnx/issues/88
