### ISSUE TITLE
ValueError: StridedSlice: only strides=1 is supported

### ISSUE THREAD

**Issue by scutzhe** [onnx/keras-onnx#86]

**Comment by jiafatom** [comment]
This is for opset 9 because slice op only supports strides=1 at that time. If you want to use strides other than 1, you need use opset 10, onnx 1.5.

**Comment by scutzhe** [comment]
thanks @jiafatom  opset10   I cannot see ,opset  is a python package?

**Comment by scutzhe** [comment]
thannks@jiafatom  opset10  and onnx 1.5.0 all  existed  , but this error occured
