### ISSUE TITLE
onnx Runtime error for keras Reshape layer with batch

### ISSUE THREAD

**Issue by yanxben** [onnx/keras-onnx#91]
Hello

I have a keras model with tensorflow backend converted to onnx with keras2onnx. I'm trying to run prediction with onnxruntime.
The conversion to onnx ends without errors.

data_format = 'channels_last'
K.set_image_data_format(data_format)

input_shape = (100, 100, 3)
x = np.random.randn(5, *input_shape).astype(np.float32)

Build model
model = keras.models.Sequential()
model.add(keras.layers.Conv2D(2, (3, 3), padding='same', input_shape=input_shape))
model.add(keras.layers.Reshape(target_shape=(1,1,100 * 100 * 2)))

Convert to onnx
onnx_model = onnxmltools.convert_keras(model, target_opset=9)
sess = onnxruntime.InferenceSession(onnx_model.SerializeToString())

Run prediction with onnx model
feed = dict([(input.name, x) for n, input in enumerate(sess.get_inputs())])
pred_onnx = sess.run(None, feed)[0]

I get the error for reshaping a batch
File "C:\Users\t-yabenn\AppData\Local\Continuum\anaconda3\envs\ilabs_onnx_temp\lib\site-packages\onnxruntime\capi\session.py", line 72, in run
return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : d:\3\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{5,100,100,2}, requested shape:{1,1,1,20000}

The reshape fails because onnx doesn't expect a batch, therefore it thinks the input is 5 times bigger than the output.
When I change the input to be x = np.random.randn(1, *input_shape).astype(np.float32) NO BATCH it runs perfectly.

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
ONNX installed from (source or binary): pip install keras2onnx onnxruntime
ONNX Runtime version: 0.4.0
keras2onnx version: 1.4.0
Python version: 3.6.0
Thnx

**Comment by jiafatom** [comment]
@yanxben We had a [fix](https://github.com/onnx/keras-onnx/pull/93), and I just tested your script and it is working now. Please pull the latest keras-onnx converter and try again, thank you!

**Comment by jiafatom** [comment]
This issue is resolved, so close it.
