### ISSUE TITLE
Bug in Keras2Onnx conversion for Bidirectional LSTM and Forward LSTM

### ISSUE THREAD

**Issue by sonu1-p** [onnx/keras-onnx#98]
I was trying to convert a Keras model to ONNX. Its conversion was successful but the inference result was not matching the Keras inference results for the same model.

On investigating, we found that this was happening because of the bias not being handled correctly in the converter. The issue is described below:

ONNX has Bias tensor defined as:
The bias tensor for input gate. Concatenation of `[Wb[iofc], Rb[iofc]]`, and `[WBb[iofc], RBb[iofc]]` (if bidirectional) along dimension 0. This tensor has shape `[num_directions, 8*hidden_size]`. 

While Keras has the shape for the same tensor as [4*hidden size] for each layer forward and backward. During conversion which is happening in the below line for forward layer:

https://github.com/onnx/keras-onnx/blob/5a37ba8e6b788eb22241349fb1a6e0fbb0b496eb/keras2onnx/ke2onnx/bidirectional.py#L81

and here for backward layer:
https://github.com/onnx/keras-onnx/blob/5a37ba8e6b788eb22241349fb1a6e0fbb0b496eb/keras2onnx/ke2onnx/bidirectional.py#L108

We simply set the R biases to zero since the current conversion code is already setting W bias to the Keras’s bias value. We expect the sum of the biases Wb + Rb to be the same as Keras’s bias since Keras uses a single bias combining both.

We tested this by setting the values of bias for onnx starting from 4*hidden size to 7*hidden size (till the end) to zero and saw that the results then matched between keras and onnx.
( by adding "b_back[4:] = np.zeros(shape=((hidden_size))) )

The same bug exists for LSTM too -
https://github.com/onnx/keras-onnx/blob/5a37ba8e6b788eb22241349fb1a6e0fbb0b496eb/keras2onnx/ke2onnx/lstm.py#L57

Wanted to bring up the issue here, so that others do not have to spend a lot of time investigating the same.

**Comment by jiafatom** [comment]
@sonu1-p Thanks for reporting this! Seems that you find the fix, can you please send a PR on this fix? and a unit test if possible (in test_layers.py)? Thank you!

**Comment by gabrielmittag** [comment]
@sonu1-p thanks a lot for reporting. This fixed the issue I posted about in [#89](https://github.com/onnx/keras-onnx/issues/89#issuecomment-497310660): 

By the way, while looking for a solution I also noticed that currently bidirectional GRUs cannot be converted to onnx, although they are actually suported in Keras.

**Comment by sonu1-p** [comment]
Sure, will put up a PR for this today.

**Comment by sonu1-p** [comment]
https://github.com/onnx/keras-onnx/pull/103

**Comment by jiafatom** [comment]
Thanks for the PR checked in.
